import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Activity, CheckCircle2, Sparkles } from "lucide-react";

type Status="BEST_PLAY"|"PLAY"|"LEAN"|"NO_PLAY";
type Pick={pick:string;probability:number;marketProbability:number;edge:number;status:Status;line?:number;price?:number|null;expected?:number};
type Game={id:string;league:"NPB";startTime:string;awayTeam:string;homeTeam:string;bookCount:number;modelReady:boolean;source:string;moneyline:Pick;total:Pick|null};
type Payload={modelVersion:string;marketStatus:string;updatedAt:string;games:Game[]};
const rank:Record<Status,number>={BEST_PLAY:4,PLAY:3,LEAN:2,NO_PLAY:1};
const label=(s:Status)=>s==="BEST_PLAY"?"Top signal":s==="PLAY"?"Strong signal":s==="LEAN"?"Lean only":"Pass";
export default function InternationalBaseball(){
 const [market,setMarket]=useState<"moneyline"|"total">("moneyline");
 const q=useQuery<Payload>({queryKey:["/api/international-baseball"],queryFn:async()=>{const r=await fetch("/api/international-baseball");if(!r.ok)throw new Error("markets unavailable");return r.json()},staleTime:90000,refetchInterval:180000});
 const games=useMemo(()=>((q.data?.games||[]).filter(g=>g.league==="NPB")),[q.data]);
 const strongest=games.flatMap(g=>{const p=market==="moneyline"?g.moneyline:g.total;return p?[{g,p}]:[]}).sort((a,b)=>rank[b.p.status]-rank[a.p.status]||b.p.edge-a.p.edge)[0];
 return <div className="space-y-6"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Activity className="h-5 w-5 text-emerald-400"/><h1 className="text-xl font-black tracking-tight">NPB Model Lab</h1></div><p className="mt-1 text-xs text-muted-foreground">Moneyline and totals ranked by model edge against the live market.</p></div><div className="flex gap-1 rounded-xl border border-border/60 bg-card p-1"><button onClick={()=>setMarket("moneyline")} className={`rounded-lg px-4 py-2 text-xs font-bold ${market==="moneyline"?"bg-muted text-foreground":"text-muted-foreground"}`}>Moneyline</button><button onClick={()=>setMarket("total")} className={`rounded-lg px-4 py-2 text-xs font-bold ${market==="total"?"bg-muted text-foreground":"text-muted-foreground"}`}>Over / Under</button></div></div>
 <section className="rounded-2xl border border-emerald-500/25 bg-emerald-500/[.06] p-4"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-400"/><div><div className="text-sm font-black">NPB official-source model</div><div className="mt-1 text-[11px] text-muted-foreground">Confirmed starters, official team results and relief context are shown when available.</div></div></div></section>
 {strongest&&<section className="rounded-2xl border border-cyan-500/35 bg-cyan-500/[.06] p-4"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-muted-foreground"><Sparkles className="h-3.5 w-3.5"/>Strongest NPB signal</div><div className="mt-2 text-base font-black">{strongest.g.awayTeam} @ {strongest.g.homeTeam}</div><div className="mt-1 text-xl font-black">{strongest.p.pick}{market==="total"&&strongest.p.line!=null?` ${strongest.p.line}`:""}</div><div className="mt-2 text-xs">Model {strongest.p.probability.toFixed(1)}% · Market {strongest.p.marketProbability.toFixed(1)}% · Edge +{strongest.p.edge.toFixed(1)}%</div></section>}
 {q.isLoading?<div className="rounded-2xl border p-10 text-center text-sm text-muted-foreground">Loading NPB model…</div>:q.isError?<div className="rounded-2xl border p-10 text-center"><div className="font-bold">NPB data is temporarily unavailable.</div></div>:games.length?<div className="grid gap-3 md:grid-cols-2">{games.map(g=>{const p=market==="moneyline"?g.moneyline:g.total;if(!p)return null;return <article key={g.id} className="rounded-2xl border border-border/55 bg-card/55 p-4"><div className="text-[10px] font-black uppercase tracking-[.16em] text-muted-foreground">NPB · {new Date(g.startTime).toLocaleString([], {month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</div><div className="mt-1.5 text-sm font-black">{g.awayTeam} <span className="text-muted-foreground">@</span> {g.homeTeam}</div><div className="mt-3 text-xl font-black">{p.pick}{market==="total"&&p.line!=null?` ${p.line}`:""}</div><div className="mt-1 text-xs text-muted-foreground">{p.probability.toFixed(1)}% model · {p.marketProbability.toFixed(1)}% market · +{p.edge.toFixed(1)}% edge</div><div className="mt-3 text-[10px] font-black uppercase">{label(p.status)}</div></article>})}</div>:<div className="rounded-2xl border p-10 text-center text-sm text-muted-foreground">No NPB games are currently on the market feed.</div>}
 </div>;
}
