import { useQuery } from '@tanstack/react-query';
import { Link } from 'wouter';
import { Activity, BarChart3, RefreshCw, Target, Gauge, Database } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';

type Bucket={range:string;n:number;predicted:number;actual:number};
type Component={key:string;label:string;n:number;status:string;lowHitRate:number|null;highHitRate:number|null;lift:number|null;lowAvgScore:number|null;highAvgScore:number|null};
type Version={modelVersion:string;sampleSize:number;brierScore:number;logLoss:number;actualHrRate:number;averageProbability:number};
type Summary={available:boolean;sampleSize:number;gradedPredictions:number;brierScore:number|null;logLoss:number|null;expectedCalibrationError:number|null;buckets:Bucket[];components?:Component[];byModelVersion?:Version[]};
const num=(v:number|null,d=4)=>v===null||!Number.isFinite(v)?'—':v.toFixed(d);
const pct=(v:number|null)=>v===null||!Number.isFinite(v)?'—':`${(v*100).toFixed(1)}%`;

export default function MLBHrPerformance(){
 const{data,isLoading,isFetching,error,refetch}=useQuery<Summary>({queryKey:['/api/mlb/home-runs/calibration',{days:30}],queryFn:async()=>{const r=await fetch('/api/mlb/home-runs/calibration?days=30');if(!r.ok)throw new Error('HR performance unavailable');return r.json()},staleTime:60_000,refetchInterval:5*60_000});
 if(isLoading)return <div className="space-y-5"><Skeleton className="h-9 w-72"/><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{Array.from({length:4}).map((_,i)=><Skeleton key={i} className="h-28"/>)}</div><Skeleton className="h-72"/></div>;
 if(error||!data)return <div className="rounded-xl border bg-card p-6"><h1 className="text-xl font-bold">HR Model Performance</h1><p className="text-sm text-muted-foreground mt-2">Performance data is unavailable right now.</p><Button variant="outline" className="mt-4" onClick={()=>refetch()}>Retry</Button></div>;
 const enough=data.gradedPredictions>=100;
 return <div className="space-y-6 max-w-6xl mx-auto">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold">HR Model Performance</h1><Badge variant="secondary">30 DAYS</Badge></div><p className="text-sm text-muted-foreground mt-1">Live grading for PreziTools home-run probabilities. This page measures the model; it does not change weights automatically.</p></div><div className="flex gap-2"><Button variant="outline" size="sm" asChild><Link href="/mlb/home-runs">Home Runs</Link></Button><Button variant="outline" size="sm" className="gap-2" onClick={()=>refetch()} disabled={isFetching}><RefreshCw className={`w-3.5 h-3.5 ${isFetching?'animate-spin':''}`}/>Refresh</Button></div></div>
  <div className={`rounded-xl border p-4 ${enough?'bg-emerald-500/5 border-emerald-500/25':'bg-amber-500/5 border-amber-500/25'}`}><div className="flex gap-3"><Database className="w-5 h-5 mt-0.5 shrink-0"/><div><p className="font-semibold">{enough?'Useful evaluation sample forming':'Early sample — collect more games'}</p><p className="text-xs text-muted-foreground mt-1">{data.gradedPredictions} graded player predictions. We should avoid retuning the model from a tiny sample.</p></div></div></div>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[{Icon:Target,label:'Graded predictions',value:String(data.gradedPredictions),sub:`${data.sampleSize} in evaluation sample`},{Icon:Gauge,label:'Brier score',value:num(data.brierScore),sub:'Lower is better'},{Icon:Activity,label:'Log loss',value:num(data.logLoss),sub:'Punishes confident misses'},{Icon:BarChart3,label:'Calibration error',value:pct(data.expectedCalibrationError),sub:'Predicted vs actual gap'}].map(({Icon,label,value,sub})=><div key={label} className="rounded-xl border bg-card p-4"><div className="flex items-center justify-between gap-2"><span className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</span><Icon className="w-4 h-4 text-primary"/></div><div className="text-2xl font-bold font-mono mt-2">{value}</div><div className="text-[11px] text-muted-foreground mt-1">{sub}</div></div>)}</div>
  <section className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Component attribution</h2><p className="text-xs text-muted-foreground mt-1">Compares the bottom 30% vs top 30% of each component score. Positive lift means high-scoring hitters homered more often. This is diagnostic evidence, not automatic weight tuning.</p><div className="mt-4 grid md:grid-cols-2 gap-3">{(data.components||[]).map(c=><div key={c.key} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-2"><div><p className="text-sm font-semibold">{c.label}</p><p className="text-[10px] text-muted-foreground">n={c.n}</p></div><Badge variant={c.status==='helping'?'default':'secondary'}>{c.status.toUpperCase()}</Badge></div>{c.lift===null?<p className="text-xs text-muted-foreground mt-3">Collecting enough graded predictions…</p>:<div className="grid grid-cols-3 gap-2 mt-3 text-center"><div><p className="text-[9px] text-muted-foreground">LOW GROUP</p><p className="font-mono text-sm">{c.lowHitRate?.toFixed(1)}%</p></div><div><p className="text-[9px] text-muted-foreground">HIGH GROUP</p><p className="font-mono text-sm">{c.highHitRate?.toFixed(1)}%</p></div><div><p className="text-[9px] text-muted-foreground">HR LIFT</p><p className={`font-mono text-sm font-bold ${(c.lift||0)>0?'text-emerald-500':(c.lift||0)<0?'text-red-500':''}`}>{(c.lift||0)>=0?'+':''}{c.lift?.toFixed(1)} pts</p></div></div>}</div>)}</div></section>
  {!!data.byModelVersion?.length&&<section className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Model versions</h2><p className="text-xs text-muted-foreground mt-1">Keeps V4 and future challengers separate so upgrades can be judged instead of blended together.</p><div className="overflow-x-auto mt-4"><table className="w-full text-xs"><thead><tr className="text-left text-muted-foreground border-b"><th className="py-2">Version</th><th>n</th><th>Brier</th><th>Log loss</th><th>Avg predicted</th><th>Actual HR</th></tr></thead><tbody>{data.byModelVersion.map(v=><tr key={v.modelVersion} className="border-b last:border-0"><td className="py-3 font-mono font-semibold">{v.modelVersion}</td><td>{v.sampleSize}</td><td>{v.brierScore.toFixed(4)}</td><td>{v.logLoss.toFixed(4)}</td><td>{v.averageProbability.toFixed(1)}%</td><td>{v.actualHrRate.toFixed(1)}%</td></tr>)}</tbody></table></div></section>}
  <section className="rounded-xl border bg-card p-5"><div className="flex flex-wrap items-end justify-between gap-2"><div><h2 className="font-semibold">Probability calibration</h2><p className="text-xs text-muted-foreground mt-1">When Prezi says a hitter has roughly X% HR probability, this checks how often hitters in that range actually homer.</p></div><span className="text-[10px] text-muted-foreground">Perfect calibration: predicted ≈ actual</span></div>{!data.buckets.length?<div className="py-12 text-center text-sm text-muted-foreground">No completed HR predictions yet. This fills automatically as games are graded.</div>:<div className="mt-5 space-y-3">{data.buckets.map(b=>{const gap=b.actual-b.predicted;return <div key={b.range} className="rounded-lg border p-3"><div className="grid grid-cols-[72px_1fr_auto] gap-3 items-center"><div><p className="font-mono font-semibold text-sm">{b.range}</p><p className="text-[9px] text-muted-foreground">n={b.n}</p></div><div className="space-y-1.5"><div className="h-2 rounded-full bg-muted overflow-hidden"><div className="h-full bg-primary" style={{width:`${Math.min(100,Math.max(0,b.predicted))}%`}}/></div><div className="h-2 rounded-full bg-muted overflow-hidden"><div className="h-full bg-emerald-500" style={{width:`${Math.min(100,Math.max(0,b.actual))}%`}}/></div></div><div className="text-right text-[10px] font-mono"><div>Prezi {b.predicted.toFixed(1)}%</div><div>Actual {b.actual.toFixed(1)}%</div><div className={Math.abs(gap)<=3?'text-emerald-500':'text-amber-500'}>{gap>=0?'+':''}{gap.toFixed(1)} pts</div></div></div></div>})}</div>}</section>
 </div>
}
