import { useQuery } from '@tanstack/react-query';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';

type Scorer={player:string;bestOdds:number;bestBook:string;modelProbability?:number;impliedProbability:number;edgePoints?:number;expectedValue?:number;qualifies?:boolean;reasons?:string[];dataStatus:'modeled'|'not-ready'};
type Game={id:string;date:string;away:string;home:string;anytimeGoal:Scorer[];firstGoal:Scorer[];qualified:{anytimeGoal:boolean;firstGoal:boolean}};
type Feed={modelVersion:string;marketStatus:string;updatedAt:string;games:Game[];health:{rawScorers:number;modeledScorers:number;notReadyScorers:number;coveragePct:number}};
const odds=(n:number)=>n>0?`+${n}`:`${n}`;
function PlayerCard({p,rank}:{p:Scorer;rank:number}){const ready=p.dataStatus==='modeled';return <Card className="overflow-hidden"><CardContent className="p-4 space-y-3"><div className="flex items-start justify-between gap-3"><div><div className="text-xs text-muted-foreground">#{rank}</div><div className="text-lg font-bold">{p.player}</div><div className="text-sm text-muted-foreground">Best price {odds(p.bestOdds)} · {p.bestBook}</div></div><Badge>{p.qualifies?'OFFICIAL PLAY':ready?'MODEL LEAN':'DATA NOT READY'}</Badge></div><div className="grid grid-cols-4 gap-2 text-center"><div><div className="text-xs text-muted-foreground">Prezi %</div><b>{ready?`${p.modelProbability?.toFixed(1)}%`:'—'}</b></div><div><div className="text-xs text-muted-foreground">Book %</div><b>{p.impliedProbability.toFixed(1)}%</b></div><div><div className="text-xs text-muted-foreground">Edge</div><b>{ready?`${(p.edgePoints??0)>=0?'+':''}${p.edgePoints?.toFixed(1)}`:'—'}</b></div><div><div className="text-xs text-muted-foreground">Bet EV</div><b>{ready?`${((p.expectedValue??0)*100).toFixed(1)}%`:'—'}</b></div></div>{p.reasons?.length?<div className="text-xs text-muted-foreground">{p.reasons.slice(0,3).join(' · ')}</div>:null}</CardContent></Card>}
function Market({title,rows}:{title:string;rows:Scorer[]}){return <section className="space-y-3"><h3 className="text-lg font-bold">{title}</h3>{rows.length?rows.map((p,i)=><PlayerCard key={`${title}-${p.player}`} p={p} rank={i+1}/>):<div className="rounded-lg border p-5 text-sm text-muted-foreground">NO PLAY — no qualifying market data available.</div>}</section>}
export default function NHL(){const {data,isLoading,error}=useQuery<Feed>({queryKey:['/api/nhl/markets'],queryFn:async()=>{const r=await fetch('/api/nhl/markets');if(!r.ok)throw new Error('Unable to load NHL markets');return r.json()},refetchInterval:5*60*1000});if(isLoading)return <div className="py-12 text-center">Loading NHL models…</div>;if(error||!data)return <div className="py-12 text-center text-muted-foreground">NHL market data is temporarily unavailable.</div>;return <div className="space-y-6"><div><h1 className="text-3xl font-black tracking-tight">NHL Models</h1><p className="text-sm text-muted-foreground">Anytime Goal · First Goal · {data.modelVersion}</p></div><div className="flex flex-wrap gap-2"><Badge variant="outline">Coverage {data.health.coveragePct}%</Badge><Badge variant="outline">Modeled {data.health.modeledScorers}/{data.health.rawScorers}</Badge></div>{data.games.length?data.games.map(g=><section key={g.id} className="space-y-4 rounded-xl border p-4"><div><div className="text-xl font-black">{g.away} @ {g.home}</div><div className="text-xs text-muted-foreground">{g.date?new Date(g.date).toLocaleString():''}</div></div><div className="grid gap-6 lg:grid-cols-2"><Market title="Anytime Goal" rows={g.anytimeGoal}/><Market title="First Goal" rows={g.firstGoal}/></div></section>):<div className="rounded-xl border p-8 text-center text-muted-foreground">No NHL games with sportsbook markets are available yet.</div>}</div>}
