import { useMemo,useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Badge } from '@/components/ui/badge';
import { Card,CardContent } from '@/components/ui/card';
import { cn } from '@/lib/utils';

type Scorer={player:string;playerId?:number;team?:string;teamAbbrev?:string;headshot?:string;teamLogo?:string;bestOdds:number;bestBook:string;modelProbability?:number;impliedProbability:number;edgePoints?:number;expectedValue?:number;qualifies?:boolean;reasons?:string[];dataStatus:'modeled'|'not-ready'};
type MlModel={modelProbability:number;marketProbability:number;edgePoints:number;expectedValue:number;qualifies:boolean;reasons:string[]};
type MlSide={team:string;teamAbbrev?:string;teamLogo?:string;bestOdds:number;bestBook:string;model:MlModel|null;dataStatus:'modeled'|'not-ready'};
type Game={id:string;date:string;away:string;home:string;awayAbbrev?:string;homeAbbrev?:string;awayLogo?:string;homeLogo?:string;moneyline:{away:MlSide;home:MlSide}|null;anytimeGoal:Scorer[];firstGoal:Scorer[]};
type Perf={totalRecorded:number;pending:number;graded:number;wins:number;losses:number;hitRate:number|null;units:number;roi:number|null;markets:{market:string;picks:number;wins:number;losses:number;hitRate:number|null;units:number;roi:number|null}[];modelPolicy:string;automaticRewriting:boolean};
type Feed={modelVersion:string;moneylineModelVersion:string;marketStatus:string;games:Game[];health:{rawScorers:number;modeledScorers:number;coveragePct:number};performance:Perf};
type Tab='anytime'|'first'|'moneyline';
const odds=(n:number)=>n>0?`+${n}`:`${n}`;
const tabs:[Tab,string][]=[['anytime','Anytime Goal'],['first','First Goal'],['moneyline','Moneyline']];
function Status({qualifies,ready}:{qualifies?:boolean;ready:boolean}){return <Badge className={cn('border-0 text-white',qualifies?'nfl-official-live':ready?'nfl-model-lean-live':'bg-muted text-muted-foreground')}>{qualifies?'OFFICIAL PLAY':ready?'MODEL LEAN':'DATA NOT READY'}</Badge>}
function PlayerCard({p,rank}:{p:Scorer;rank:number}){const ready=p.dataStatus==='modeled';return <Card className="overflow-hidden border-slate-700/35 bg-gradient-to-br from-card via-card to-slate-950/10"><CardContent className="p-4 space-y-3"><div className="flex justify-between gap-3"><div className="flex min-w-0 items-center gap-3">{p.headshot?<img src={p.headshot} alt="" className="h-14 w-14 shrink-0 rounded-full border border-white/10 bg-slate-900 object-cover object-top shadow-lg"/>:<div className="h-14 w-14 shrink-0 rounded-full border bg-muted"/>}<div className="min-w-0"><div className="text-xs text-muted-foreground">#{rank}{p.teamAbbrev?` · ${p.teamAbbrev}`:''}</div><div className="truncate text-lg font-bold">{p.player}</div><div className="text-sm text-muted-foreground">{odds(p.bestOdds)} · {p.bestBook}</div></div>{p.teamLogo?<img src={p.teamLogo} alt="" className="h-8 w-8 shrink-0 object-contain drop-shadow"/>:null}</div><Status qualifies={p.qualifies} ready={ready}/></div><div className="grid grid-cols-4 gap-2 rounded-lg bg-slate-950/10 p-2 text-center text-sm"><div>Prezi<br/><b>{ready?`${p.modelProbability?.toFixed(1)}%`:'—'}</b></div><div>Book<br/><b>{p.impliedProbability.toFixed(1)}%</b></div><div>Edge<br/><b>{ready?p.edgePoints?.toFixed(1):'—'}</b></div><div>EV<br/><b>{ready?`${((p.expectedValue??0)*100).toFixed(1)}%`:'—'}</b></div></div>{p.reasons?.length?<div className="text-xs text-muted-foreground">{p.reasons.slice(0,3).join(' · ')}</div>:null}</CardContent></Card>}
function MoneylineCard({s}:{s:MlSide}){const x=s.model;return <Card className="overflow-hidden border-slate-700/35 bg-gradient-to-br from-card via-card to-slate-950/10"><CardContent className="p-5 space-y-4"><div className="flex justify-between gap-3"><div className="flex items-center gap-3">{s.teamLogo?<img src={s.teamLogo} alt="" className="h-12 w-12 object-contain drop-shadow-lg"/>:null}<div><div className="text-lg font-black">{s.team}</div><div className="text-sm text-muted-foreground">{odds(s.bestOdds)} · {s.bestBook}</div></div></div><Status qualifies={x?.qualifies} ready={Boolean(x)}/></div>{x?<><div className="grid grid-cols-4 rounded-lg bg-slate-950/10 p-2 text-center text-sm"><div>Prezi<br/><b>{x.modelProbability}%</b></div><div>Book<br/><b>{x.marketProbability}%</b></div><div>Edge<br/><b>{x.edgePoints}</b></div><div>EV<br/><b>{(x.expectedValue*100).toFixed(1)}%</b></div></div>{x.reasons?.length?<div className="text-xs text-muted-foreground">{x.reasons.slice(0,3).join(' · ')}</div>:null}</>:null}</CardContent></Card>}
function Performance({p}:{p:Perf}){return <Card><CardContent className="p-5 space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-xl font-black">NHL V1 Forward-Test Performance</h2><p className="text-xs text-muted-foreground">Frozen production predictions · no automatic model rewriting</p></div><Badge variant="outline">{p.graded} graded · {p.pending} pending</Badge></div><div className="grid grid-cols-2 gap-3 md:grid-cols-5 text-center"><div><div className="text-xs text-muted-foreground">Record</div><b>{p.wins}-{p.losses}</b></div><div><div className="text-xs text-muted-foreground">Hit Rate</div><b>{p.hitRate==null?'—':`${p.hitRate}%`}</b></div><div><div className="text-xs text-muted-foreground">Units</div><b>{p.units>0?'+':''}{p.units}</b></div><div><div className="text-xs text-muted-foreground">ROI</div><b>{p.roi==null?'—':`${p.roi}%`}</b></div><div><div className="text-xs text-muted-foreground">Recorded</div><b>{p.totalRecorded}</b></div></div></CardContent></Card>}
function GameHeader({g}:{g:Game}){return <div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/5 pb-4"><div className="flex items-center gap-3">{g.awayLogo?<img src={g.awayLogo} alt="" className="h-10 w-10 object-contain"/>:null}<div><div className="text-xl font-black">{g.away} <span className="text-muted-foreground">@</span> {g.home}</div><div className="text-xs text-muted-foreground">{g.date?new Date(g.date).toLocaleString():''}</div></div>{g.homeLogo?<img src={g.homeLogo} alt="" className="h-10 w-10 object-contain"/>:null}</div></div>}
export default function NHL(){const [tab,setTab]=useState<Tab>('anytime');const {data,isLoading,error}=useQuery<Feed>({queryKey:['/api/nhl/markets'],queryFn:async()=>{const r=await fetch('/api/nhl/markets');if(!r.ok)throw new Error();return r.json()},refetchInterval:5*60*1000});const marketLabel=useMemo(()=>tabs.find(x=>x[0]===tab)?.[1]??'', [tab]);if(isLoading)return <div className="py-12 text-center">Loading NHL models…</div>;if(error||!data)return <div className="py-12 text-center text-muted-foreground">NHL market data is temporarily unavailable.</div>;return <div className="space-y-6"><div><h1 className="text-3xl font-black">NHL Models</h1><p className="text-sm text-muted-foreground">Separate market boards · frozen forward-test tracking · best sportsbook price</p></div><Performance p={data.performance}/><div className="flex flex-wrap gap-2"><Badge variant="outline">Coverage {data.health.coveragePct}%</Badge><Badge variant="outline">Modeled {data.health.modeledScorers}/{data.health.rawScorers}</Badge></div><div className="grid grid-cols-3 gap-2 rounded-xl border bg-card/70 p-2 shadow-sm">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={cn('rounded-lg px-3 py-3 text-xs font-black transition sm:text-sm',tab===key?'bg-gradient-to-r from-slate-950 via-slate-700 to-slate-950 text-white shadow-[0_0_20px_rgba(148,163,184,.22)]':'text-muted-foreground hover:bg-muted hover:text-foreground')} aria-pressed={tab===key}>{label}</button>)}</div><div className="text-xs font-bold uppercase tracking-[.18em] text-muted-foreground">{marketLabel} Board</div>{data.games.length?data.games.map(g=><section key={g.id} className="space-y-5 rounded-xl border bg-card/60 p-4 shadow-sm"><GameHeader g={g}/>{tab==='moneyline'?g.moneyline?<div className="grid gap-3 sm:grid-cols-2"><MoneylineCard s={g.moneyline.away}/><MoneylineCard s={g.moneyline.home}/></div>:<div className="rounded-lg border p-5 text-sm text-muted-foreground">DATA NOT READY — no moneyline market.</div>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(tab==='anytime'?g.anytimeGoal:g.firstGoal).length?(tab==='anytime'?g.anytimeGoal:g.firstGoal).map((p,i)=><PlayerCard key={`${g.id}-${p.player}`} p={p} rank={i+1}/>):<div className="rounded-lg border p-5 text-sm text-muted-foreground">NO PLAY — no qualifying {marketLabel.toLowerCase()} data available.</div>}</div>}</section>):<div className="rounded-xl border p-8 text-center text-muted-foreground">No NHL games with sportsbook markets are available yet.</div>}</div>}
