import 'dotenv/config';
import express, { type Request, Response, NextFunction } from "express";
import session from "express-session";
import connectPgSimple from "connect-pg-simple";
import { Pool, neonConfig } from "@neondatabase/serverless";
import ws from "ws";
import { registerRoutes } from "./routes";
import { setupVite, serveStatic, log } from "./vite";
import { authMiddleware, requireAdmin } from "./auth";
import { createDailySyncService } from "./dailySync";
import { storage } from "./storage";
import { fetchMlbRfiMarkets, getCachedMlbRfiQuotes, valueFromCachedQuotesForTeams } from "./mlbOdds";
import { getCalibrationSummary } from "./mlbCalibration";
import { evaluateMlbModelHealth } from "./mlbModelHealth";
import { registerCalibrationSourceRoute } from "./mlbCalibrationSources";
import { getMlbIntegritySummary } from "./mlbIntegrity";
import { getMlbAutoGradeStatus, startMlbAutoGradeScheduler } from "./mlbAutoGrade";
import { getMlbClosingLineSummary } from "./mlbClosingLine";
import { getPredictionHistory } from "./mlbPredictionSnapshots";
import { registerMlbHistoryRoutes } from "./mlbHistory";
import { getMlbLockFunnel } from "./mlbLockFunnel";
import { registerMlbV4PublicRoutes } from "./mlbPublicV4Routes";
import { registerProductionCleanupRoutes } from "./productionCleanupRoutes";
import { fetchNflMarkets } from "./nflMarkets";
import { getNflMoneylineShadowDiagnostics, gradePendingNflMoneylineShadow } from "./nflMoneylineShadowLedger";
import { captureNflTdPredictions, captureNflTdClosingLines, getNflTdPerformance, gradePendingNflTdPredictions } from "./nflTdCalibration";
import { registerWhopBillingRoutes } from "./whopBilling";
import { registerWnbaFeature } from "./wnbaFeature";
const app=express();app.set('trust proxy',1);app.disable('x-powered-by');neonConfig.webSocketConstructor=ws;const production=process.env.NODE_ENV==='production';const configuredSessionSecret=process.env.SESSION_SECRET?.trim();const databaseUrl=process.env.DATABASE_URL?.trim();if(production&&!configuredSessionSecret)throw new Error('SESSION_SECRET is required in production.');if(production&&!databaseUrl)throw new Error('DATABASE_URL is required in production.');const sessionSecret=configuredSessionSecret||'development-only-session-secret';const appDbPool=databaseUrl?new Pool({connectionString:databaseUrl}):null;const sessionStore=appDbPool?(()=>{const PgSession=connectPgSimple(session);return new PgSession({pool:appDbPool,tableName:'session',createTableIfMissing:true});})():undefined;app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:false,limit:'1mb'}));app.use(session({...(sessionStore?{store:sessionStore}:{}),secret:sessionSecret,resave:false,saveUninitialized:false,cookie:{secure:production,httpOnly:true,maxAge:30*24*60*60*1000,sameSite:'lax'}}));app.use(authMiddleware);registerWhopBillingRoutes(app);registerWnbaFeature(app);
app.get('/api/health',async(_req,res)=>res.json({status:'ok',modelVersion:'v4-live',generatedAt:new Date().toISOString()}));
app.get('/api/admin/nfl/shadow-diagnostics',requireAdmin,async(req,res)=>{try{const days=typeof req.query.days==='string'?Number(req.query.days):30;const gradedNow=await gradePendingNflMoneylineShadow(20);return res.json({...await getNflMoneylineShadowDiagnostics(days),gradedNow});}catch{return res.status(500).json({error:'Unable to load NFL shadow diagnostics'});}});
app.get('/api/nfl/markets',async(_req,res)=>{try{const data=await fetchNflMarkets();void Promise.all(data.games.map(async game=>{await captureNflTdPredictions(game);await captureNflTdClosingLines(game);})).catch(error=>console.warn('[NFL TD] ledger capture failed:',error));res.setHeader('Cache-Control','public, max-age=120, stale-while-revalidate=600');return res.json(data);}catch(error){console.error('[NFL Markets] Error:',error);return res.status(502).json({error:'Unable to load NFL market data'});}});
app.get('/api/nfl/td-performance',async(req,res)=>{try{const days=typeof req.query.days==='string'?Number(req.query.days):90;if(!Number.isFinite(days)||days<1||days>365)return res.status(400).json({error:'days must be a number from 1 to 365'});await gradePendingNflTdPredictions(20);res.setHeader('Cache-Control','public, max-age=60, stale-while-revalidate=300');return res.json(await getNflTdPerformance(days));}catch(error){console.error('[NFL TD Performance] Error:',error);return res.status(500).json({error:'Unable to load NFL TD performance'});}});
registerProductionCleanupRoutes(app);registerMlbV4PublicRoutes(app);registerCalibrationSourceRoute(app,requireAdmin);registerMlbHistoryRoutes(app,requireAdmin);const httpServer=await registerRoutes(app);if(production){startMlbAutoGradeScheduler();setInterval(()=>{void (async()=>{try{const data=await fetchNflMarkets();await Promise.all(data.games.map(game=>captureNflTdClosingLines(game)));}catch(error){console.error('[NFL TD Close] Error:',error);}void gradePendingNflMoneylineShadow(20);void gradePendingNflTdPredictions(20);})();},5*60*1000);}app.use((err:any,_req:Request,res:Response,_next:NextFunction)=>{console.error('[Server Error]',err);res.status(err.status||500).json({message:err.message||'Internal Server Error'});});if(app.get('env')==='development')await setupVite(app,httpServer);else serveStatic(app);const port=parseInt(process.env.PORT||'5000',10);httpServer.listen({port,host:'0.0.0.0'},()=>log(`serving on port ${port}`));
