import type { Express } from "express";
import { Pool, neonConfig } from "@neondatabase/serverless";
import ws from "ws";

neonConfig.webSocketConstructor = ws;
const pool = process.env.DATABASE_URL ? new Pool({ connectionString: process.env.DATABASE_URL }) : null;
const API_BASE = "https://api.the-odds-api.com/v4/sports";
const MODEL_VERSION = "intl-baseball-v1";
type League = "KBO" | "NPB";
type Status = "BEST_PLAY" | "PLAY" | "LEAN" | "NO_PLAY";
type ApiOutcome={name:string;price:number;point?:number};
type ApiMarket={key:string;outcomes:ApiOutcome[]};
type ApiBook={key:string;title:string;last_update:string;markets:ApiMarket[]};
type ApiGame={id:string;sport_key:string;commence_time:string;home_team:string;away_team:string;bookmakers:ApiBook[]};
function americanToProb(o:number){return o<0?(-o)/((-o)+100):100/(o+100)}
function fairTwo(a:number,b:number){const x=americanToProb(a),y=americanToProb(b),z=x+y;return z?[x/z,y/z]:[.5,.5]}
function status(edge:number):Status{const e=Math.abs(edge);return e>=.065?"BEST_PLAY":e>=.045?"PLAY":e>=.025?"LEAN":"NO_PLAY"}
function median(v:number[]){if(!v.length)return null;const s=[...v].sort((a,b)=>a-b);const m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}
async function ensureTable(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS international_baseball_predictions(id varchar(220) PRIMARY KEY,league text NOT NULL,event_id text NOT NULL,game_start_at timestamptz NOT NULL,home_team text NOT NULL,away_team text NOT NULL,market text NOT NULL,selection text NOT NULL,line real,model_probability real NOT NULL,market_probability real NOT NULL,edge real NOT NULL,status text NOT NULL,model_version text NOT NULL,locked_at timestamptz NOT NULL DEFAULT now(),result text,created_at timestamptz NOT NULL DEFAULT now(),graded_at timestamptz); CREATE INDEX IF NOT EXISTS international_baseball_predictions_start_idx ON international_baseball_predictions(game_start_at DESC);`)}
function sportKey(l:League){return l==="KBO"?"baseball_kbo":"baseball_npb"}
async function fetchLeague(league:League):Promise<ApiGame[]>{const key=process.env.ODDS_API_KEY?.trim();if(!key)return[];const url=`${API_BASE}/${sportKey(league)}/odds?regions=us,eu,au&markets=h2h,totals&oddsFormat=american&apiKey=${encodeURIComponent(key)}`;const r=await fetch(url,{headers:{"User-Agent":"PreziTools/1.0"}});if(!r.ok)throw new Error(`${league} odds returned ${r.status}`);return r.json() as Promise<ApiGame[]>}
function modelGame(league:League,g:ApiGame){const h2h=g.bookmakers.flatMap(b=>{const m=b.markets.find(x=>x.key==="h2h");if(!m)return[];const h=m.outcomes.find(x=>x.name===g.home_team),a=m.outcomes.find(x=>x.name===g.away_team);return h&&a?[{book:b.title,home:h.price,away:a.price}]:[]});const fair=h2h.map(x=>fairTwo(x.home,x.away));const home=median(fair.map(x=>x[0]))??.5,away=1-home;const homeEdge=home-.5,awayEdge=away-.5;const mlPick=home>=away?g.home_team:g.away_team,mlProb=Math.max(home,away),mlEdge=Math.max(homeEdge,awayEdge);const totals=g.bookmakers.flatMap(b=>{const m=b.markets.find(x=>x.key==="totals");if(!m)return[];const over=m.outcomes.find(x=>x.name.toLowerCase()==="over"),under=m.outcomes.find(x=>x.name.toLowerCase()==="under");return over&&under&&over.point!=null?[{book:b.title,line:over.point,over:over.price,under:under.price}]:[]});const line=median(totals.map(x=>x.line));const totalFair=totals.map(x=>fairTwo(x.over,x.under));const over=median(totalFair.map(x=>x[0]))??.5,under=1-over;const totalPick=over>=under?"Over":"Under",totalProb=Math.max(over,under),totalEdge=totalProb-.5;return{id:g.id,league,startTime:g.commence_time,awayTeam:g.away_team,homeTeam:g.home_team,bookCount:g.bookmakers.length,moneyline:{pick:mlPick,probability:+(mlProb*100).toFixed(1),marketProbability:+(mlProb*100).toFixed(1),edge:+(mlEdge*100).toFixed(1),status:status(mlEdge)},total:line==null?null:{pick:totalPick,line,probability:+(totalProb*100).toFixed(1),marketProbability:+(totalProb*100).toFixed(1),edge:+(totalEdge*100).toFixed(1),status:status(totalEdge)}}}
async function lock(rows:any[]){if(!pool)return;await ensureTable();for(const g of rows){if(new Date(g.startTime).getTime()<=Date.now())continue;for(const [market,p] of [["moneyline",g.moneyline],["total",g.total]] as const){if(!p||p.status==="NO_PLAY")continue;const id=`${g.league}:${g.id}:${market}:${MODEL_VERSION}`;await pool.query(`INSERT INTO international_baseball_predictions(id,league,event_id,game_start_at,home_team,away_team,market,selection,line,model_probability,market_probability,edge,status,model_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(id) DO NOTHING`,[id,g.league,g.id,g.startTime,g.homeTeam,g.awayTeam,market,p.pick,"line" in p?p.line:null,p.probability/100,p.marketProbability/100,p.edge/100,p.status,MODEL_VERSION])}}}
async function slate(){const [kbo,npb]=await Promise.all([fetchLeague("KBO"),fetchLeague("NPB")]);const games=[...kbo.map(g=>modelGame("KBO",g)),...npb.map(g=>modelGame("NPB",g))];void lock(games).catch(e=>console.warn("[Intl Baseball] lock failed",e));return{modelVersion:MODEL_VERSION,marketStatus:process.env.ODDS_API_KEY?"live":"configuration_required",updatedAt:new Date().toISOString(),games}}
export function registerInternationalBaseballRoutes(app:Express){app.get("/api/international-baseball",async(_req,res)=>{try{const data=await slate();res.setHeader("Cache-Control","public, max-age=90, stale-while-revalidate=300");return res.json(data)}catch(e){console.error("[Intl Baseball]",e);return res.status(502).json({error:"Unable to load KBO / NPB markets"})}});app.get("/api/international-baseball/performance",async(_req,res)=>{if(!pool)return res.json({graded:0,wins:0,losses:0,winRate:null});try{await ensureTable();const r=await pool.query(`SELECT count(*) FILTER(WHERE result IN ('won','lost'))::int graded,count(*) FILTER(WHERE result='won')::int wins,count(*) FILTER(WHERE result='lost')::int losses FROM international_baseball_predictions`);const x=r.rows[0]??{};return res.json({...x,winRate:x.graded?x.wins/x.graded:null,modelVersion:MODEL_VERSION})}catch{return res.status(500).json({error:"Unable to load performance"})}})}
