export type League = "KBO" | "NPB";

export type OfficialTeamMetric = { key:string; games:number; winPct:number; homePct:number|null; awayPct:number|null; runsPerGame:number; runsAllowedPerGame:number };
export type OfficialGameResult = { league:League; date:string; awayKey:string; homeKey:string; awayScore:number; homeScore:number };
const UA="PreziTools/1.0 (+https://prezitools.com)"; const YEAR=new Date().getUTCFullYear();
let metricCache:{expiresAt:number;value:Record<League,Map<string,OfficialTeamMetric>>}|null=null;
const resultCache=new Map<string,{expiresAt:number;value:OfficialGameResult[]}>();
function htmlDecode(v:string){return v.replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">")}
function text(v:string){return htmlDecode(v.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim()}
function tableRows(html:string){const out:string[][]=[];for(const row of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const cells=[...row[1].matchAll(/<(?:td|th)\b[^>]*>([\s\S]*?)<\/(?:td|th)>/gi)].map(m=>text(m[1]));if(cells.length)out.push(cells)}return out}
async function getHtml(url:string){const r=await fetch(url,{headers:{"User-Agent":UA,Accept:"text/html,application/xhtml+xml"}});if(!r.ok)throw new Error(`Official baseball source returned ${r.status}: ${url}`);return r.text()}
function pctFromRecord(v:string){const m=v.match(/(\d+)\s*-\s*(\d+)/);if(!m)return null;const w=+m[1],l=+m[2];return w+l?w/(w+l):null}
function norm(v:string){return v.toLowerCase().normalize("NFKD").replace(/[^a-z0-9가-힣一-龯ァ-ヶ]/g,"")}
const aliases:Array<[string,string[]]>=[
["kbo:lg",["lg","lg twins"]],["kbo:kt",["kt","kt wiz","kt wiz suwon"]],["kbo:samsung",["samsung","samsung lions"]],["kbo:kia",["kia","kia tigers"]],["kbo:doosan",["doosan","doosan bears"]],["kbo:nc",["nc","nc dinos"]],["kbo:hanwha",["hanwha","hanwha eagles"]],["kbo:lotte",["lotte","lotte giants"]],["kbo:ssg",["ssg","ssg landers"]],["kbo:kiwoom",["kiwoom","kiwoom heroes"]],
["npb:hanshin",["hanshin","hanshin tigers","阪神","阪神タイガース"]],["npb:yomiuri",["yomiuri","yomiuri giants","読売","読売ジャイアンツ","巨人"]],["npb:dena",["dena","yokohama dena baystars","yokohama dena","横浜dena","横浜denaベイスターズ"]],["npb:yakult",["yakult","tokyo yakult swallows","東京ヤクルト","東京ヤクルトスワローズ","ヤクルト"]],["npb:chunichi",["chunichi","chunichi dragons","中日","中日ドラゴンズ"]],["npb:hiroshima",["hiroshima","hiroshima toyo carp","広島","広島東洋","広島東洋カープ"]],["npb:softbank",["softbank","fukuoka softbank hawks","福岡ソフトバンク","福岡ソフトバンクホークス","ソフトバンク"]],["npb:nipponham",["nippon-ham","nippon ham","hokkaido nippon-ham fighters","北海道日本ハム","北海道日本ハムファイターズ","日本ハム"]],["npb:orix",["orix","orix buffaloes","オリックス","オリックス・バファローズ"]],["npb:rakuten",["rakuten","tohoku rakuten golden eagles","東北楽天","東北楽天ゴールデンイーグルス","楽天"]],["npb:seibu",["seibu","saitama seibu lions","埼玉西武","埼玉西武ライオンズ","西武"]],["npb:lotte",["lotte","chiba lotte marines","千葉ロッテ","千葉ロッテマリーンズ","ロッテ"]]];
const aliasMap=new Map<string,string>();for(const [key,vals] of aliases)for(const v of vals)aliasMap.set(norm(v),key);
export function canonicalTeamKey(league:League,value:string){const n=norm(value);const direct=aliasMap.get(n);if(direct?.startsWith(`${league.toLowerCase()}:`))return direct;let best:string|null=null,bestLen=0;for(const [a,k] of aliasMap){if(!k.startsWith(`${league.toLowerCase()}:`)||a.length<2)continue;if((n.includes(a)||a.includes(n))&&a.length>bestLen){best=k;bestLen=a.length}}return best}
function numeric(v:string){const n=Number(v.replace(/,/g,""));return Number.isFinite(n)?n:null}
async function fetchKboMetrics(){const html=await getHtml("https://eng.koreabaseball.com/Standings/TeamStandings.aspx");const rows=tableRows(html);const out=new Map<string,OfficialTeamMetric>();for(const c of rows){const rank=numeric(c[0]??"");if(rank==null||rank<1||rank>10)continue;const key=canonicalTeamKey("KBO",c[1]??"");const g=numeric(c[2]??""),w=numeric(c[3]??""),l=numeric(c[4]??""),pct=numeric(c[6]??"");if(!key||g==null||g<=0)continue;const wp=pct!=null&&pct<=1?pct:(w!=null&&l!=null&&w+l>0?w/(w+l):null);if(wp==null)continue;out.set(key,{key,games:g,winPct:wp,homePct:pctFromRecord(c[9]??""),awayPct:pctFromRecord(c[10]??""),runsPerGame:0,runsAllowedPerGame:0})}
// KBO's standings table layout changes and does not reliably expose season runs in fixed columns.
// Keep win/home/road strength valid even when run columns are unavailable; the model will use league scoring priors for totals.
return out}
function parseNpbStandings(html:string,out:Map<string,OfficialTeamMetric>){for(const c of tableRows(html)){const key=canonicalTeamKey("NPB",c[0]??"");const g=numeric(c[1]??""),w=numeric(c[2]??""),l=numeric(c[3]??""),pct=numeric(c[5]??"");if(!key||g==null||g<=0)continue;const wp=pct!=null&&pct<=1?pct:(w!=null&&l!=null&&w+l?w/(w+l):null);if(wp==null)continue;out.set(key,{key,games:g,winPct:wp,homePct:pctFromRecord(c[7]??""),awayPct:pctFromRecord(c[8]??""),runsPerGame:0,runsAllowedPerGame:0})}}
function parseNpbBatting(html:string,out:Map<string,OfficialTeamMetric>){for(const c of tableRows(html)){const key=canonicalTeamKey("NPB",c[0]??"");const existing=key?out.get(key):null;if(!existing)continue;const nums=c.slice(1).map(numeric).filter((n):n is number=>n!=null);const games=nums.find(n=>n>=80&&n<=160)??existing.games;const plausibleRuns=nums.filter(n=>n>=250&&n<=1000);const runs=plausibleRuns.length?plausibleRuns[0]:null;if(runs!=null&&games>0)existing.runsPerGame=runs/games}}
function parseNpbPitching(html:string,out:Map<string,OfficialTeamMetric>){for(const c of tableRows(html)){const key=canonicalTeamKey("NPB",c[0]??"");const existing=key?out.get(key):null;if(!existing)continue;const nums=c.slice(1).map(numeric).filter((n):n is number=>n!=null);const games=nums.find(n=>n>=80&&n<=160)??existing.games;const plausibleRuns=nums.filter(n=>n>=250&&n<=1000);const runsAllowed=plausibleRuns.length?plausibleRuns[plausibleRuns.length-1]:null;if(runsAllowed!=null&&games>0)existing.runsAllowedPerGame=runsAllowed/games}}
async function fetchNpbMetrics(){const urls=[`https://npb.jp/bis/eng/${YEAR}/stats/std_c.html`,`https://npb.jp/bis/eng/${YEAR}/stats/std_p.html`,`https://npb.jp/bis/${YEAR}/stats/tmb_c.html`,`https://npb.jp/bis/${YEAR}/stats/tmb_p.html`,`https://npb.jp/bis/${YEAR}/stats/tmp_c.html`,`https://npb.jp/bis/${YEAR}/stats/tmp_p.html`];const html=await Promise.all(urls.map(getHtml));const out=new Map<string,OfficialTeamMetric>();parseNpbStandings(html[0],out);parseNpbStandings(html[1],out);parseNpbBatting(html[2],out);parseNpbBatting(html[3],out);parseNpbPitching(html[4],out);parseNpbPitching(html[5],out);return out}
export async function getOfficialTeamMetrics(){if(metricCache&&metricCache.expiresAt>Date.now())return metricCache.value;const [kbo,npb]=await Promise.all([fetchKboMetrics(),fetchNpbMetrics()]);const value={KBO:kbo,NPB:npb};metricCache={value,expiresAt:Date.now()+15*60_000};return value}
async function fetchKboResults(date:string){const html=await getHtml(`https://eng.koreabaseball.com/Schedule/Scoreboard.aspx?searchDate=${encodeURIComponent(date)}`);const plain=text(html);const token="(LG|KT|SAMSUNG|KIA|DOOSAN|NC|HANWHA|LOTTE|SSG|KIWOOM)";const re=new RegExp(`${token}\\s+(\\d+)\\s+FINAL\\s+(\\d+)\\s+${token}`,"gi");const out:OfficialGameResult[]=[];for(const m of plain.matchAll(re)){const awayKey=canonicalTeamKey("KBO",m[1]),homeKey=canonicalTeamKey("KBO",m[4]);if(awayKey&&homeKey)out.push({league:"KBO",date,awayKey,homeKey,awayScore:+m[2],homeScore:+m[3]})}return out}
async function fetchNpbResults(date:string){const d=new Date(`${date}T12:00:00Z`),month=String(d.getUTCMonth()+1).padStart(2,"0"),day=d.getUTCDate();const html=await getHtml(`https://npb.jp/games/${d.getUTCFullYear()}/schedule_${month}_detail.html`);const out:OfficialGameResult[]=[];let currentDay:number|null=null;const team="(阪神|巨人|DeNA|ヤクルト|中日|広島|ソフトバンク|日本ハム|オリックス|楽天|西武|ロッテ)",re=new RegExp(`${team}\\s+(\\d+)\\s*-\\s*(\\d+)\\s+${team}`);for(const c of tableRows(html)){const dm=(c[0]??"").match(/^(\d{1,2})\/(\d{1,2})/);if(dm)currentDay=+dm[2];if(currentDay!==day)continue;const m=c.join(" ").match(re);if(!m)continue;const awayKey=canonicalTeamKey("NPB",m[1]),homeKey=canonicalTeamKey("NPB",m[4]);if(awayKey&&homeKey)out.push({league:"NPB",date,awayKey,homeKey,awayScore:+m[2],homeScore:+m[3]})}return out}
export async function getOfficialResults(league:League,date:string){const ck=`${league}:${date}`,cached=resultCache.get(ck);if(cached&&cached.expiresAt>Date.now())return cached.value;const value=league==="KBO"?await fetchKboResults(date):await fetchNpbResults(date);resultCache.set(ck,{value,expiresAt:Date.now()+10*60_000});return value}
export function dateInLeagueZone(date:Date,league:League){const timeZone=league==="KBO"?"Asia/Seoul":"Asia/Tokyo";const p=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date);const get=(t:string)=>p.find(x=>x.type===t)?.value??"";return `${get("year")}-${get("month")}-${get("day")}`}
