import type { Express } from 'express';
import { Pool, neonConfig } from '@neondatabase/serverless';
import ws from 'ws';

neonConfig.webSocketConstructor=ws;
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL}):null;
let initialized=false;

async function init(){if(!pool||initialized)return;await pool.query(`CREATE TABLE IF NOT EXISTS mlb_hr_prediction_history (
 id text PRIMARY KEY, prediction_date text NOT NULL, game_pk bigint NOT NULL, player_id bigint NOT NULL, player text NOT NULL,
 team text NOT NULL, opponent text NOT NULL, model_version text NOT NULL, probability double precision NOT NULL,
 prezi_hr_score integer NOT NULL, confidence integer NOT NULL, tier text NOT NULL, lineup_confirmed boolean NOT NULL,
 components jsonb, market jsonb, predicted_at timestamptz NOT NULL DEFAULT now(), outcome integer, home_runs integer,
 graded_at timestamptz, UNIQUE(prediction_date,game_pk,player_id,model_version)
)`);await pool.query(`CREATE INDEX IF NOT EXISTS mlb_hr_prediction_history_date_idx ON mlb_hr_prediction_history(prediction_date)`);initialized=true}

type Candidate={gamePk:number;playerId:number;player:string;team:string;opponent:string;probability:number;preziHrScore:number;confidence:number;tier:string;lineupConfirmed:boolean;scoreComponents?:unknown;market?:unknown};
export async function recordHrSnapshot(body:any){if(!pool||!body?.date||!Array.isArray(body?.candidates))return;await init();const model=String(body.modelVersion||'unknown');for(const c of body.candidates as Candidate[]){if(!c?.gamePk||!c?.playerId||!Number.isFinite(c.probability))continue;const id=`${body.date}:${c.gamePk}:${c.playerId}:${model}`;await pool.query(`INSERT INTO mlb_hr_prediction_history(id,prediction_date,game_pk,player_id,player,team,opponent,model_version,probability,prezi_hr_score,confidence,tier,lineup_confirmed,components,market)
 VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb,$15::jsonb)
 ON CONFLICT(id) DO NOTHING`,[id,body.date,c.gamePk,c.playerId,c.player,c.team,c.opponent,model,c.probability/100,c.preziHrScore,c.confidence,c.tier,c.lineupConfirmed,JSON.stringify(c.scoreComponents??null),JSON.stringify(c.market??null)])}}

async function fetchJson(url:string){const r=await fetch(url,{signal:AbortSignal.timeout(10000),headers:{'User-Agent':'PreziTools/1.0'}});if(!r.ok)throw new Error(`MLB ${r.status}`);return r.json() as Promise<any>}
export async function gradeHrPredictions(limit=300){if(!pool)return{graded:0};await init();const pending=await pool.query(`SELECT id,game_pk,player_id FROM mlb_hr_prediction_history WHERE outcome IS NULL AND prediction_date <= (now() AT TIME ZONE 'America/New_York')::date::text ORDER BY prediction_date ASC LIMIT $1`,[limit]);let graded=0;const games=new Map<number,any>();for(const row of pending.rows){try{let game=games.get(Number(row.game_pk));if(!game){game=await fetchJson(`https://statsapi.mlb.com/api/v1.1/game/${row.game_pk}/feed/live`);games.set(Number(row.game_pk),game)}if(game?.gameData?.status?.abstractGameState!=='Final')continue;const box=game?.liveData?.boxscore;const teams=[box?.teams?.away,box?.teams?.home];let found:any=null;for(const t of teams){const p=t?.players?.[`ID${row.player_id}`];if(p){found=p;break}}if(!found)continue;const hr=Number(found?.stats?.batting?.homeRuns??0);await pool.query(`UPDATE mlb_hr_prediction_history SET outcome=$2,home_runs=$3,graded_at=now() WHERE id=$1 AND outcome IS NULL`,[row.id,hr>0?1:0,hr]);graded++}catch(e){console.warn('[MLB HR Calibration] grade failed',row.id,e)}}return{graded}}

const COMPONENT_LABELS:Record<string,string>={power:'Statcast Power',pitcherRisk:'Pitcher Risk',pitchMatchup:'Pitch Matchup',parkFit:'Handed Park Fit',directionFit:'Pull-Air Direction',recentForm:'Recent Form',environment:'Environment',opportunity:'Opportunity'};
function componentAttribution(rows:any[]){const keys=Object.keys(COMPONENT_LABELS);return keys.map(key=>{const xs=rows.map(r=>({score:Number(r.components?.[key]),y:Number(r.outcome)})).filter(x=>Number.isFinite(x.score)&&(x.y===0||x.y===1));if(xs.length<8)return{key,label:COMPONENT_LABELS[key],n:xs.length,status:'collecting',lowHitRate:null,highHitRate:null,lift:null,lowAvgScore:null,highAvgScore:null};xs.sort((a,b)=>a.score-b.score);const cut=Math.max(3,Math.floor(xs.length*.3));const low=xs.slice(0,cut),high=xs.slice(-cut);const rate=(a:typeof xs)=>a.reduce((s,x)=>s+x.y,0)/a.length;const avg=(a:typeof xs)=>a.reduce((s,x)=>s+x.score,0)/a.length;const lowRate=rate(low),highRate=rate(high),lift=highRate-lowRate;return{key,label:COMPONENT_LABELS[key],n:xs.length,status:xs.length<40?'early':lift>.02?'helping':lift<-.02?'hurting':'neutral',lowHitRate:Math.round(lowRate*1000)/10,highHitRate:Math.round(highRate*1000)/10,lift:Math.round(lift*1000)/10,lowAvgScore:Math.round(avg(low)*10)/10,highAvgScore:Math.round(avg(high)*10)/10}})}

export async function getHrCalibration(days=30){if(!pool)return{available:false,sampleSize:0,gradedPredictions:0,brierScore:null,logLoss:null,expectedCalibrationError:null,buckets:[],components:[],byModelVersion:[]};await init();const r=await pool.query(`SELECT probability,outcome,model_version,components FROM mlb_hr_prediction_history WHERE outcome IS NOT NULL AND prediction_date >= ((now() AT TIME ZONE 'America/New_York')::date-$1::int)::text`,[days]);const rows=r.rows.map(x=>({p:Number(x.probability),y:Number(x.outcome),model:String(x.model_version),components:x.components||{}})).filter(x=>Number.isFinite(x.p)&&(x.y===0||x.y===1));if(!rows.length)return{available:true,sampleSize:0,gradedPredictions:0,brierScore:null,logLoss:null,expectedCalibrationError:null,buckets:[],components:[],byModelVersion:[]};const metrics=(xs:typeof rows)=>{const b=xs.reduce((s,x)=>s+(x.p-x.y)**2,0)/xs.length;const ll=xs.reduce((s,x)=>{const p=Math.max(.001,Math.min(.999,x.p));return s-(x.y*Math.log(p)+(1-x.y)*Math.log(1-p))},0)/xs.length;return{sampleSize:xs.length,brierScore:Math.round(b*10000)/10000,logLoss:Math.round(ll*10000)/10000,actualHrRate:Math.round(xs.reduce((s,x)=>s+x.y,0)/xs.length*1000)/10,averageProbability:Math.round(xs.reduce((s,x)=>s+x.p,0)/xs.length*1000)/10}};const overall=metrics(rows);const buckets=[] as any[];let ece=0;for(let lo=0;lo<.5;lo+=.05){const xs=rows.filter(x=>x.p>=lo&&x.p<lo+.05);if(!xs.length)continue;const predicted=xs.reduce((s,x)=>s+x.p,0)/xs.length,actual=xs.reduce((s,x)=>s+x.y,0)/xs.length;ece+=xs.length/rows.length*Math.abs(predicted-actual);buckets.push({range:`${Math.round(lo*100)}-${Math.round((lo+.05)*100)}%`,n:xs.length,predicted:Math.round(predicted*1000)/10,actual:Math.round(actual*1000)/10})}const versions=[...new Set(rows.map(x=>x.model))].map(model=>({modelVersion:model,...metrics(rows.filter(x=>x.model===model))})).sort((a,b)=>b.sampleSize-a.sampleSize);return{available:true,sampleSize:rows.length,gradedPredictions:rows.length,brierScore:overall.brierScore,logLoss:overall.logLoss,expectedCalibrationError:Math.round(ece*10000)/10000,buckets,components:componentAttribution(rows),byModelVersion:versions}}

let schedulerStarted=false;
export function registerMlbHrCalibration(app:Express){app.use('/api/mlb/home-runs',(req,res,next)=>{if(req.method!=='GET')return next();const json=res.json.bind(res);res.json=((body:any)=>{if(body?.candidates)void recordHrSnapshot(body).catch(e=>console.warn('[MLB HR Calibration] snapshot failed',e));return json(body)}) as typeof res.json;next()});app.get('/api/mlb/home-runs/calibration',async(req,res)=>{try{const days=Math.max(1,Math.min(365,Number(req.query.days??30)||30));void gradeHrPredictions(150).catch(()=>{});res.setHeader('Cache-Control','public, max-age=60, stale-while-revalidate=300');return res.json(await getHrCalibration(days))}catch(e){console.error('[MLB HR Calibration] summary failed',e);return res.status(500).json({error:'Unable to load HR calibration'})}});if(process.env.NODE_ENV==='production'&&!schedulerStarted){schedulerStarted=true;setInterval(()=>void gradeHrPredictions(300).catch(e=>console.error('[MLB HR Calibration] auto-grade failed',e)),30*60*1000)}}
