import type { Express, RequestHandler } from "express";
import { Pool, neonConfig } from "@neondatabase/serverless";
import ws from "ws";
import { getPredictionHistory } from "./mlbPredictionSnapshots.js";
import { gradePendingMlbHrBestPlays } from "./mlbHrTracking.js";
import { gradePendingNflMoneylineShadow } from "./nflMoneylineShadowLedger.js";
import { gradePendingNflTdPredictions } from "./nflTdCalibration.js";
import { bestPlaySelectionKey, captureBestPlaySelections, getBestPlaySelectionKeys } from "./bestPlaysLedger.js";

neonConfig.webSocketConstructor = ws;
const outcomePool = process.env.DATABASE_URL ? new Pool({ connectionString: process.env.DATABASE_URL }) : null;
function outcomeFromScore(score:string|null|undefined):"NRFI"|"YRFI"|null{if(!score)return null;const match=score.trim().match(/^(\d+)\s*-\s*(\d+)$/);if(!match)return null;const away=Number(match[1]),home=Number(match[2]);if(!Number.isSafeInteger(away)||!Number.isSafeInteger(home)||away<0||home<0)return null;return away===0&&home===0?"NRFI":"YRFI";}
function etDateOffset(offsetDays=0):string{const parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const y=Number(parts.find(p=>p.type==="year")?.value),m=Number(parts.find(p=>p.type==="month")?.value),d=Number(parts.find(p=>p.type==="day")?.value);return new Date(Date.UTC(y,m-1,d+offsetDays,12)).toISOString().slice(0,10);}
function requestedOutcomeDate(v:unknown):string|null{if(v==null||v===""||v==="today")return etDateOffset(0);if(v==="yesterday")return etDateOffset(-1);if(typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(v))return v;return null;}
async function tableExists(name:string):Promise<boolean>{if(!outcomePool)return false;const result=await outcomePool.query("SELECT to_regclass($1) AS name",[`public.${name}`]);return Boolean(result.rows[0]?.name);}
async function getBestPlayOutcomes(date:string){const rows:any[]=[];if(!outcomePool)return{date,outcomes:rows};
try{await Promise.all([gradePendingMlbHrBestPlays(120),gradePendingNflMoneylineShadow(30),gradePendingNflTdPredictions(30)]);}catch(error){console.warn("[Best Plays Outcomes] pre-read grading pass failed",error);}
if(await tableExists("mlb_prediction_snapshots")){try{const result=await outcomePool.query(`SELECT s.game_id,s.matchup,s.recommendation,s.probability,s.outcome,s.first_inning_score,s.graded_at,c.context->>'playStatus' AS play_status FROM mlb_prediction_snapshots s LEFT JOIN mlb_prediction_context c ON c.prediction_date=s.prediction_date AND c.game_id=s.game_id AND c.model_version=s.model_version WHERE (s.game_start_at AT TIME ZONE 'UTC' AT TIME ZONE 'America/New_York')::date=$1::date AND s.locked_at IS NOT NULL AND s.graded_at IS NOT NULL AND s.recommendation IN ('NRFI','YRFI') AND s.outcome IN ('NRFI','YRFI') AND (c.context->>'playStatus' IN ('BEST_PLAY','PLAY') OR (c.context->>'playStatus'='LEAN' AND s.value_play=true)) AND s.probability>=0.535 ORDER BY s.graded_at DESC NULLS LAST`,[date]);for(const row of result.rows)rows.push({id:`mlb-${row.game_id}`,sport:"MLB",market:row.recommendation,matchup:row.matchup,pick:row.recommendation,probability:Math.round(Number(row.probability)*1000)/10,result:row.outcome===row.recommendation?"won":"lost",actual:`${row.outcome}${row.first_inning_score?` · 1st inning ${row.first_inning_score}`:""}`,gradedAt:row.graded_at,href:"/mlb"});}catch(error){console.warn("[Best Plays Outcomes] MLB rows unavailable",error);}}
if(await tableExists("mlb_hr_best_play_ledger")){try{const result=await outcomePool.query(`SELECT id,game_pk,player_id,player_name,team,opponent,model_probability,hr_count,won,graded_at FROM mlb_hr_best_play_ledger WHERE (game_start_at AT TIME ZONE 'America/New_York')::date=$1::date AND graded_at IS NOT NULL AND won IS NOT NULL ORDER BY graded_at DESC NULLS LAST`,[date]);for(const row of result.rows)rows.push({id:`mlb-hr-${row.game_pk}-${row.player_id}`,sport:"MLB",market:"Home Run",matchup:`${row.team} vs ${row.opponent}`,pick:`${row.player_name} Home Run`,probability:Number(row.model_probability),result:row.won===true?"won":"lost",actual:Number(row.hr_count)>0?`${row.player_name} hit ${Number(row.hr_count)} HR`:"No home run",gradedAt:row.graded_at,href:"/mlb/home-runs"});}catch(error){console.warn("[Best Plays Outcomes] MLB HR rows unavailable",error);}}
if(await tableExists("wnba_prediction_ledger")){try{const result=await outcomePool.query(`SELECT l.espn_game_id,l.player_name,l.team,l.model_probability,l.model_rank,l.actual_first_scorer,l.actual_first_scorer_team,l.won,l.graded_at,e.team_a,e.team_b FROM wnba_prediction_ledger l LEFT JOIN wnba_opening_evidence e ON e.espn_game_id=l.espn_game_id WHERE (l.game_start_at AT TIME ZONE 'America/New_York')::date=$1::date AND l.graded_at IS NOT NULL AND l.model_rank=1 AND l.model_probability>=10 ORDER BY l.model_probability DESC,l.graded_at DESC NULLS LAST LIMIT 2`,[date]);for(const row of result.rows){const teams=[row.team_a,row.team_b].filter(Boolean);rows.push({id:`wnba-${row.espn_game_id}-${row.model_rank}`,sport:"WNBA",market:"First Basket",matchup:teams.length===2?`${teams[0]} vs ${teams[1]}`:`${row.team} game`,pick:row.player_name,probability:Number(row.model_probability),result:row.won===true?"won":"lost",actual:row.actual_first_scorer?`${row.actual_first_scorer}${row.actual_first_scorer_team?` (${row.actual_first_scorer_team})`:""}`:"Result verified",gradedAt:row.graded_at,href:"/wnba"});}}catch(error){console.warn("[Best Plays Outcomes] WNBA rows unavailable",error);}}
if(await tableExists("fb_prediction_ledger")){try{const result=await outcomePool.query(`SELECT espn_game_id,player_name,team,model_probability,model_rank,actual_first_scorer,actual_first_scorer_team,won,graded_at FROM fb_prediction_ledger WHERE (game_start_at AT TIME ZONE 'America/New_York')::date=$1::date AND graded_at IS NOT NULL AND is_top_pick=true AND model_probability>=12 ORDER BY model_probability DESC,graded_at DESC NULLS LAST LIMIT 3`,[date]);for(const row of result.rows)rows.push({id:`nba-${row.espn_game_id}-${row.team}-${row.player_name}`,sport:"NBA",market:"First Basket",matchup:`${row.team} game`,pick:row.player_name,probability:Number(row.model_probability),result:row.won===true?"won":"lost",actual:row.actual_first_scorer?`${row.actual_first_scorer}${row.actual_first_scorer_team?` (${row.actual_first_scorer_team})`:""}`:"Result verified",gradedAt:row.graded_at,href:"/nba"});}catch(error){console.warn("[Best Plays Outcomes] NBA rows unavailable",error);}}
if(await tableExists("nfl_moneyline_shadow")){try{const result=await outcomePool.query(`SELECT game_id,away_team,home_team,v1_away_probability,v1_home_probability,home_won,winner_team,graded_at FROM nfl_moneyline_shadow WHERE (game_start_at AT TIME ZONE 'America/New_York')::date=$1::date AND graded_at IS NOT NULL AND home_won IS NOT NULL AND greatest(coalesce(v1_away_probability,0),coalesce(v1_home_probability,0))>=55 ORDER BY graded_at DESC NULLS LAST`,[date]);for(const row of result.rows){const away=Number(row.v1_away_probability??0),home=Number(row.v1_home_probability??0),pickHome=home>=away,probability=pickHome?home:away,pick=pickHome?String(row.home_team):String(row.away_team),won=pickHome?row.home_won===true:row.home_won===false;rows.push({id:`nfl-ml-${row.game_id}`,sport:"NFL",market:"Moneyline",matchup:`${row.away_team} @ ${row.home_team}`,pick:`${pick} ML`,probability,result:won?"won":"lost",actual:row.winner_team?`${row.winner_team} won`:"Final result verified",gradedAt:row.graded_at,href:"/nfl"});}}catch(error){console.warn("[Best Plays Outcomes] NFL moneyline rows unavailable",error);}}
if(await tableExists("nfl_td_prediction_history")){try{const result=await outcomePool.query(`WITH per_game AS (SELECT *,row_number() OVER(PARTITION BY game_id,market ORDER BY expected_value DESC NULLS LAST,edge_points DESC NULLS LAST,model_probability DESC) AS game_rank FROM nfl_td_prediction_history WHERE (game_start_at AT TIME ZONE 'America/New_York')::date=$1::date AND model_version='nfl-td-v3' AND grade_status IN ('win','loss') AND graded_at IS NOT NULL AND edge_points>=2.5 AND expected_value>=0.05),per_market AS (SELECT *,row_number() OVER(PARTITION BY market ORDER BY CASE WHEN edge_points>=5 AND expected_value>=0.14 THEN 0 ELSE 1 END,model_probability DESC) AS market_rank FROM per_game WHERE game_rank=1) SELECT id,game_id,market,player,model_probability,grade_status,first_td_player,graded_at FROM per_market WHERE market_rank<=2 ORDER BY graded_at DESC NULLS LAST`,[date]);for(const row of result.rows){const market=String(row.market)==="first"?"First TD":"Anytime TD";rows.push({id:`nfl-td-${market}-${row.game_id}-${row.player}`,sport:"NFL",market,matchup:"NFL game",pick:String(row.player),probability:Number(row.model_probability),result:row.grade_status==="win"?"won":"lost",actual:String(row.market)==="first"&&row.first_td_player?`First TD: ${row.first_td_player}`:row.grade_status==="win"?"Touchdown verified":"No qualifying touchdown",gradedAt:row.graded_at,href:"/nfl"});}}catch(error){console.warn("[Best Plays Outcomes] NFL TD rows unavailable",error);}}
const savedKeys=await getBestPlaySelectionKeys(date);const verifiedRows=savedKeys.size?rows.filter(row=>savedKeys.has(bestPlaySelectionKey(String(row.id)))):rows;
verifiedRows.sort((a,b)=>new Date(b.gradedAt||0).getTime()-new Date(a.gradedAt||0).getTime());return{date,outcomes:verifiedRows};}
async function getCalibration(days:number){const end=etDateOffset(-1),all:any[]=[];for(let offset=1;offset<=days;offset++){const date=etDateOffset(-offset);const payload=await getBestPlayOutcomes(date);for(const row of payload.outcomes)all.push({...row,date});}const families=[{key:"standard",label:"Standard probability plays",test:(r:any)=>!["Home Run","First Basket","First Basket #2","First Basket #3","First TD","Anytime TD"].includes(String(r.market)),bands:[[50,55,"50–54.9%"],[55,60,"55–59.9%"],[60,Infinity,"60%+"]]},{key:"longshot",label:"Player scoring props",test:(r:any)=>["Home Run","First Basket","First Basket #2","First Basket #3","First TD","Anytime TD"].includes(String(r.market)),bands:[[0,10,"Under 10%"],[10,20,"10–19.9%"],[20,Infinity,"20%+"]]}];const groups=families.map(f=>({key:f.key,label:f.label,bands:f.bands.map(([min,max,label])=>{const plays=all.filter(f.test).filter(r=>Number.isFinite(Number(r.probability))&&Number(r.probability)>=Number(min)&&Number(r.probability)<Number(max));const wins=plays.filter(r=>r.result==="won").length;return{label,plays:plays.length,wins,losses:plays.length-wins,winRate:plays.length?Math.round(wins/plays.length*1000)/10:null,averageModelProbability:plays.length?Math.round(plays.reduce((s,r)=>s+Number(r.probability),0)/plays.length*10)/10:null};})}));return{windowDays:days,through:end,total:all.length,groups};}

export function registerMlbHistoryRoutes(app:Express,_requireAdmin?:RequestHandler):void{
app.post("/api/best-plays/selections",async(req,res)=>{try{const result=await captureBestPlaySelections(req);res.setHeader("Cache-Control","no-store");return res.status(201).json(result);}catch(error){const code=error instanceof Error?error.message:"invalid_request";return res.status(code==="origin_not_allowed"?403:400).json({error:code});}});
app.get("/api/mlb/history",async(req,res)=>{try{const requestedDays=typeof req.query.days==="string"?Number(req.query.days):30;if(!Number.isFinite(requestedDays)||requestedDays<1||requestedDays>365)return res.status(400).json({error:"days must be a number from 1 to 365"});const rows=await getPredictionHistory(requestedDays);let excludedIntegrityRows=0;const verified=rows.filter(row=>row.lockedAt&&(row.outcome==="NRFI"||row.outcome==="YRFI")&&(row.recommendation==="NRFI"||row.recommendation==="YRFI")).filter(row=>{const scoreOutcome=outcomeFromScore(row.firstInningScore);const valid=scoreOutcome!==null&&scoreOutcome===row.outcome;if(!valid)excludedIntegrityRows++;return valid;}).map(row=>({date:row.date,gameId:row.gameId,matchup:row.matchup,recommendation:row.recommendation,probability:row.probability,confidence:row.confidence??null,modelVersion:row.modelVersion,gameStartAt:row.gameStartAt??null,lockedAt:row.lockedAt??null,outcome:row.outcome,result:row.outcome===row.recommendation?"won":"lost",firstInningScore:row.firstInningScore??null,marketValue:row.marketValue??null}));const wins=verified.filter(row=>row.result==="won").length,losses=verified.filter(row=>row.result==="lost").length;res.setHeader("Cache-Control","public, max-age=30, stale-while-revalidate=120");return res.json({windowDays:Math.round(requestedDays),generatedAt:new Date().toISOString(),total:verified.length,wins,losses,winRate:verified.length?wins/verified.length:null,integrity:{excludedRows:excludedIntegrityRows,note:excludedIntegrityRows?"Rows whose saved outcome disagrees with the authoritative first-inning score are hidden from the public record.":"All displayed results agree with the authoritative first-inning score."},predictions:verified});}catch(error){console.error("[MLB History] Error:",error);return res.status(500).json({error:"Unable to load verified MLB prediction history"});}});
app.get("/api/best-plays/outcomes",async(req,res)=>{try{const date=requestedOutcomeDate(req.query.date);if(!date)return res.status(400).json({error:"date must be today, yesterday, or YYYY-MM-DD"});const payload=await getBestPlayOutcomes(date);const wins=payload.outcomes.filter((row:any)=>row.result==="won").length,losses=payload.outcomes.filter((row:any)=>row.result==="lost").length;res.setHeader("Cache-Control","public, max-age=60, stale-while-revalidate=300");return res.json({date:payload.date,resetTimeZone:"America/New_York",total:payload.outcomes.length,wins,losses,outcomes:payload.outcomes});}catch(error){console.error("[Best Plays Outcomes] Error:",error);return res.status(500).json({error:"Unable to load verified Best Plays outcomes"});}});
app.get("/api/best-plays/calibration",async(req,res)=>{try{const days=typeof req.query.days==="string"?Number(req.query.days):30;if(!Number.isFinite(days)||days<7||days>60)return res.status(400).json({error:"days must be from 7 to 60"});res.setHeader("Cache-Control","public, max-age=300, stale-while-revalidate=900");return res.json(await getCalibration(Math.round(days)));}catch(error){console.error("[Best Plays Calibration] Error:",error);return res.status(500).json({error:"Unable to load Best Plays calibration"});}});
}
