export type HrDirectionProfile={playerId:number;bbe:number;airPct:number|null;pullPct:number|null;straightPct:number|null;oppoPct:number|null;pullAirPct:number|null;straightAirPct:number|null;oppoAirPct:number|null};
export type HrDirectionFit={score:number;multiplier:number;available:boolean;reliability:number;pullAirPct:number|null;explanation:string};
const SAVANT='https://baseballsavant.mlb.com/leaderboard/batted-ball',CACHE_TTL_MS=6*60*60*1000;let cache:{season:number;expiresAt:number;value:{batters:Map<number,HrDirectionProfile>;available:boolean}}|null=null;
function csvLine(line:string){const out:string[]=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){out.push(cur);cur=''}else cur+=c}out.push(cur);return out}
function norm(v:string){return v.toLowerCase().replace(/[^a-z0-9]/g,'')}
function num(v:string|undefined){if(!v)return null;const n=Number(v.replace(/[% ,]/g,''));return Number.isFinite(n)?n:null}
function field(row:Record<string,string>,names:string[]){for(const n of names){const target=norm(n);for(const [k,v] of Object.entries(row))if(norm(k)===target)return v}return undefined}
function parse(text:string){const lines=text.trim().split(/\r?\n/).filter(Boolean),out=new Map<number,HrDirectionProfile>();if(lines.length<2)return out;const headers=csvLine(lines[0]).map(x=>x.trim());for(const line of lines.slice(1)){const vals=csvLine(line),row:Record<string,string>={};headers.forEach((h,i)=>row[h]=vals[i]??'');const id=num(field(row,['player_id','playerid','id'])),bbe=num(field(row,['bbe','batted_ball_events','battedballevents']));if(id==null||bbe==null)continue;out.set(id,{playerId:id,bbe,airPct:num(field(row,['air_rate','air_pct','air%','air'])),pullPct:num(field(row,['pull_rate','pull_pct','pull%','pull'])),straightPct:num(field(row,['straight_rate','straight_pct','straight%','straight'])),oppoPct:num(field(row,['oppo_rate','oppo_pct','oppo%','oppo'])),pullAirPct:num(field(row,['pull_air_rate','pull_air_pct','pull air%','pullair'])),straightAirPct:num(field(row,['straight_air_rate','straight_air_pct','straight air%','straightair'])),oppoAirPct:num(field(row,['oppo_air_rate','oppo_air_pct','oppo air%','oppoair']))})}return out}
export async function fetchHrDirectionProfiles(season:number){if(cache&&cache.season===season&&cache.expiresAt>Date.now())return cache.value;const params=new URLSearchParams();params.append('season[]',String(season));params.set('type','batter');params.append('gameType[]','R');params.set('min','1');params.set('minSplit','1');params.set('csv','true');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch(`${SAVANT}?${params}`,{signal:controller.signal,headers:{'User-Agent':'PreziTools/1.0'}});if(!r.ok)throw new Error(`Baseball Savant batted-ball ${r.status}`);const batters=parse(await r.text()),value={batters,available:batters.size>50};cache={season,expiresAt:Date.now()+CACHE_TTL_MS,value};return value}catch(e){console.warn('[MLB HR Direction] unavailable; neutral direction fit used:',e);return{batters:new Map<number,HrDirectionProfile>(),available:false}}finally{clearTimeout(timer)}}
export function directionFit(profile:HrDirectionProfile|undefined,parkFactor:number):HrDirectionFit{if(!profile||profile.bbe<20||profile.pullAirPct==null)return{score:50,multiplier:1,available:false,reliability:0,pullAirPct:profile?.pullAirPct??null,explanation:'Pull-air sample unavailable; neutral direction adjustment used'};const reliability=Math.max(.30,Math.min(1,profile.bbe/180)),leaguePullAir=17.5;const rawScore=Math.max(0,Math.min(100,50+(profile.pullAirPct-leaguePullAir)*2.2));const regressed=50+(rawScore-50)*reliability;const parkSignal=Math.max(-1,Math.min(1,(parkFactor-1)/.12));const hitterSignal=(regressed-50)/50;const interaction=hitterSignal*(.65+.35*Math.max(0,parkSignal));const multiplier=Math.max(.94,Math.min(1.08,1+interaction*.08));const score=Math.round(Math.max(0,Math.min(100,regressed+(parkSignal>0?Math.max(0,regressed-50)*parkSignal*.18:0))));return{score,multiplier:Math.round(multiplier*1000)/1000,available:true,reliability:Math.round(reliability*1000)/1000,pullAirPct:profile.pullAirPct,explanation:`Pull AIR ${profile.pullAirPct.toFixed(1)}% across ${profile.bbe} BBE · ${Math.round(reliability*100)}% sample reliability`}}
