const ESPN_SITE = 'https://site.api.espn.com/apis/site/v2/sports/football/nfl';
const ESPN_WEB = 'https://site.web.api.espn.com/apis/common/v3/sports/football/nfl';
const MODEL_CACHE_MS = 6 * 60 * 60 * 1000;

export type ModelConfidence = 'watch' | 'strong' | 'elite';
export type ModelResult = { modelProbability:number; edgePoints:number; expectedValue:number; confidence:ModelConfidence; qualifies:boolean; reasons:string[]; };
export type ModelPlayerMarket = { player:string; bestOdds:number; bestBook:string; impliedProbability:number; quoteCount:number; };
export type ModelTeamSide = { abbreviation:string; name:string; record:string|null; };
export type ModelGameInput = { id?:string; date?:string; away:ModelTeamSide; home:ModelTeamSide; };

type TeamProfile={ppg:number|null;papg:number|null;ypg:number|null};
type PlayerBaseline={team:string;position:string;td:number;games:number;touches:number;targets:number;yards:number;currentGames:number;priorGames:number};

const jsonCache=new Map<string,{expires:number;value:unknown}>();
const rosterCache=new Map<string,{expires:number;players:{id:string;name:string;position:string}[]}>();
function clamp(v:number,min:number,max:number){return Math.max(min,Math.min(max,v));}
function norm(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');}
function sigmoid(x:number){return 1/(1+Math.exp(-x));}
function americanProfit(odds:number){return odds>0?odds/100:100/Math.abs(odds);}
function americanImpliedPct(odds:number){return (odds>0?100/(odds+100):Math.abs(odds)/(Math.abs(odds)+100))*100;}
function ev(probabilityPct:number,odds:number){const p=probabilityPct/100;return p*americanProfit(odds)-(1-p);}
function parseRecord(record:string|null){if(!record)return null;const m=record.match(/(\d+)\s*-\s*(\d+)(?:\s*-\s*(\d+))?/);if(!m)return null;const w=Number(m[1]),l=Number(m[2]),t=Number(m[3]??0);const games=w+l+t;return games?((w+0.5*t)/games):null;}
async function getJson<T>(url:string,ttl=MODEL_CACHE_MS):Promise<T>{const hit=jsonCache.get(url);if(hit&&hit.expires>Date.now())return hit.value as T;const c=new AbortController();const timer=setTimeout(()=>c.abort(),9000);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'PreziTools/1.0'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const value=await r.json() as T;jsonCache.set(url,{expires:Date.now()+ttl,value});return value;}finally{clearTimeout(timer);}}
function collectStats(node:unknown,out:Map<string,number>){if(!node||typeof node!=='object')return;if(Array.isArray(node)){for(const x of node)collectStats(x,out);return;}const o=node as Record<string,unknown>;const name=typeof o.name==='string'?o.name:typeof o.abbreviation==='string'?o.abbreviation:null;const value=typeof o.value==='number'?o.value:typeof o.value==='string'&&Number.isFinite(Number(o.value))?Number(o.value):null;if(name&&value!==null)out.set(norm(name),value);for(const v of Object.values(o))collectStats(v,out);}
function stat(map:Map<string,number>,...names:string[]){for(const n of names){const v=map.get(norm(n));if(v!==undefined&&Number.isFinite(v))return v;}return null;}
async function teamProfile(team:string):Promise<TeamProfile>{const season=new Date().getUTCFullYear();const urls=[`${ESPN_SITE}/teams/${encodeURIComponent(team)}/statistics?season=${season}`,`${ESPN_SITE}/teams/${encodeURIComponent(team)}/statistics?season=${season-1}`];for(const url of urls){try{const payload=await getJson<unknown>(url);const m=new Map<string,number>();collectStats(payload,m);const ppg=stat(m,'pointsPerGame','avgPoints','points');const papg=stat(m,'pointsAllowedPerGame','avgPointsAllowed','pointsAgainst');const ypg=stat(m,'yardsPerGame','totalYardsPerGame');if(ppg!==null||ypg!==null)return{ppg,papg,ypg};}catch{}}return{ppg:null,papg:null,ypg:null};}
export async function modelMoneyline(game:ModelGameInput,awayOdds:number|null,homeOdds:number|null){const [away,home]=await Promise.all([teamProfile(game.away.abbreviation),teamProfile(game.home.abbreviation)]);const awayRecord=parseRecord(game.away.record)??0.5,homeRecord=parseRecord(game.home.record)??0.5;let rating=(homeRecord-awayRecord)*2.4+0.12;if(home.ppg!==null&&away.ppg!==null)rating+=(home.ppg-away.ppg)*0.055;if(home.papg!==null&&away.papg!==null)rating+=(away.papg-home.papg)*0.045;if(home.ypg!==null&&away.ypg!==null)rating+=(home.ypg-away.ypg)*0.0015;const homeProb=clamp(sigmoid(rating)*100,20,80),awayProb=100-homeProb;const build=(prob:number,odds:number|null):ModelResult|null=>{if(odds===null||!Number.isFinite(odds))return null;const implied=americanImpliedPct(odds),edge=prob-implied,expected=ev(prob,odds);const confidence:ModelConfidence=edge>=6&&expected>=0.08?'elite':edge>=3&&expected>=0.04?'strong':'watch';return{modelProbability:+prob.toFixed(1),edgePoints:+edge.toFixed(1),expectedValue:+expected.toFixed(3),confidence,qualifies:edge>=3&&expected>=0.04,reasons:['independent team-strength rating','current/previous-season scoring baseline','home-field adjustment']};};return{away:build(awayProb,awayOdds),home:build(homeProb,homeOdds)};}
async function roster(team:string){const key=team.toUpperCase(),hit=rosterCache.get(key);if(hit&&hit.expires>Date.now())return hit.players;try{const payload=await getJson<any>(`${ESPN_SITE}/teams/${encodeURIComponent(team)}/roster`);const players:{id:string;name:string;position:string}[]=[];const walk=(node:any)=>{if(!node)return;if(Array.isArray(node)){node.forEach(walk);return;}if(typeof node!=='object')return;const id=node.id??node.athlete?.id,name=node.fullName??node.displayName??node.athlete?.fullName??node.athlete?.displayName,position=node.position?.abbreviation??node.athlete?.position?.abbreviation;if(id&&name)players.push({id:String(id),name:String(name),position:String(position??'')});Object.values(node).forEach(walk);};walk(payload);const unique=[...new Map(players.map(p=>[p.id,p])).values()];rosterCache.set(key,{expires:Date.now()+MODEL_CACHE_MS,players:unique});return unique;}catch{return[];}}
async function seasonPlayerStats(id:string,season:number){try{const payload=await getJson<unknown>(`${ESPN_WEB}/athletes/${encodeURIComponent(id)}/stats?season=${season}&seasontype=2`);const m=new Map<string,number>();collectStats(payload,m);const rush=stat(m,'rushingTouchdowns','rushTouchdowns')??0,rec=stat(m,'receivingTouchdowns','recTouchdowns')??0,games=stat(m,'gamesPlayed','games')??0,carries=stat(m,'rushingAttempts','carries')??0,receptions=stat(m,'receptions')??0,targets=stat(m,'receivingTargets','targets')??0,rushYds=stat(m,'rushingYards')??0,recYds=stat(m,'receivingYards')??0;return{td:rush+rec,games,touches:carries+receptions,targets,yards:rushYds+recYds};}catch{return{td:0,games:0,touches:0,targets:0,yards:0};}}
async function playerBaseline(playerName:string,teams:string[]):Promise<PlayerBaseline|null>{for(const team of teams){const players=await roster(team),target=norm(playerName);const found=players.find(p=>norm(p.name)===target)||players.find(p=>norm(p.name).endsWith(target)||target.endsWith(norm(p.name)));if(!found)continue;const year=new Date().getUTCFullYear();const [cur,prior]=await Promise.all([seasonPlayerStats(found.id,year),seasonPlayerStats(found.id,year-1)]);const currentWeight=cur.games>=4?0.7:cur.games>0?0.45:0,priorWeight=currentWeight?1-currentWeight:1;const blend=(a:number,b:number)=>a*currentWeight+b*priorWeight;return{team,position:found.position,td:blend(cur.td,prior.td),games:Math.max(1,blend(cur.games,prior.games)),touches:blend(cur.touches,prior.touches),targets:blend(cur.targets,prior.targets),yards:blend(cur.yards,prior.yards),currentGames:cur.games,priorGames:prior.games};}return null;}
function positionScoringRole(position:string,touchesPerGame:number,targetsPerGame:number){if(position==='RB')return clamp(0.96+touchesPerGame/95,0.96,1.18);if(position==='TE')return clamp(0.95+targetsPerGame/55,0.95,1.10);if(position==='WR')return clamp(0.94+targetsPerGame/65,0.94,1.10);if(position==='QB')return 0.78;return 0.82;}
export async function qualifyTdMarkets(game:ModelGameInput,rows:ModelPlayerMarket[],kind:'anytime'|'first'){
 const output:Array<ModelPlayerMarket&ModelResult>=[],teams=[game.away.abbreviation,game.home.abbreviation];const [awayProfile,homeProfile]=await Promise.all([teamProfile(game.away.abbreviation),teamProfile(game.home.abbreviation)]);
 for(const row of rows){const base=await playerBaseline(row.player,teams);if(!base)continue;const own=base.team.toUpperCase()===game.home.abbreviation.toUpperCase()?homeProfile:awayProfile;const opp=base.team.toUpperCase()===game.home.abbreviation.toUpperCase()?awayProfile:homeProfile;const tdPerGame=base.td/base.games,touchesPerGame=base.touches/base.games,targetsPerGame=base.targets/base.games,yardsPerGame=base.yards/base.games;const role=positionScoringRole(base.position,touchesPerGame,targetsPerGame);const offense=clamp((own.ppg??22.5)/22.5,0.78,1.25),defense=clamp((opp.papg??22.5)/22.5,0.82,1.20);const usageSignal=clamp((touchesPerGame/18)*0.55+(targetsPerGame/7)*0.30+(yardsPerGame/85)*0.15,0.15,1.35);const regressedTdRate=0.62*tdPerGame+0.38*clamp(usageSignal*0.55,0.08,0.85);const scoringLambda=clamp(regressedTdRate*role*Math.sqrt(offense*defense),0.02,1.35);let probability:number;if(kind==='anytime')probability=(1-Math.exp(-scoringLambda))*100;else{const teamEarlyShare=clamp(0.46+(offense-1)*0.18+(defense-1)*0.10+(base.team.toUpperCase()===game.home.abbreviation.toUpperCase()?0.025:0),0.34,0.62);const earlyRole=clamp(0.50*usageSignal+0.30*role+0.20*clamp(tdPerGame/0.7,0.2,1.35),0.25,1.35);probability=(1-Math.exp(-scoringLambda))*teamEarlyShare*earlyRole*27;}probability=clamp(probability,kind==='anytime'?2:0.6,kind==='anytime'?74:22);const edge=probability-row.impliedProbability,expected=ev(probability,row.bestOdds);const minBooks=kind==='first'?2:1,minEdge=kind==='first'?3.0:2.5,minEv=kind==='first'?0.07:0.05;const qualifies=row.quoteCount>=minBooks&&edge>=minEdge&&expected>=minEv&&(kind==='first'?probability>=3.5:probability>=16);const confidence:ModelConfidence=qualifies?(edge>=7&&expected>=0.12?'elite':'strong'):'watch';output.push({...row,modelProbability:+probability.toFixed(1),edgePoints:+edge.toFixed(1),expectedValue:+expected.toFixed(3),confidence,qualifies,reasons:[kind==='first'?'early scoring opportunity model':'anytime scoring opportunity model',`Usage: ${touchesPerGame.toFixed(1)} touches/game · ${targetsPerGame.toFixed(1)} targets/game · ${yardsPerGame.toFixed(0)} yards/game`,`TD rate: ${tdPerGame.toFixed(2)} blended TD/game with regression`,`Role: ${base.position||'skill'} scoring adjustment ×${role.toFixed(2)}`,`Environment: ${own.ppg?.toFixed(1)??'22.5'} team PPG vs ${opp.papg?.toFixed(1)??'22.5'} opponent points allowed`,`Market: ${row.quoteCount} book${row.quoteCount===1?'':'s'} · ${row.impliedProbability.toFixed(1)}% implied`]});}
 const sorted=output.sort((a,b)=>Number(b.qualifies)-Number(a.qualifies)||b.expectedValue-a.expectedValue||b.modelProbability-a.modelProbability).slice(0,kind==='first'?8:10);
 const official=sorted.filter(x=>x.qualifies);
 if(game.id&&game.date&&official.length){void import('./nflTdCalibration.js').then(async({captureNflTdPredictions})=>{const stub:any={id:game.id,date:game.date,anytimeTd:kind==='anytime'?official:[],firstTd:kind==='first'?official:[]};await captureNflTdPredictions(stub);}).catch(e=>console.warn('[NFL TD Ledger] capture failed:',e));}
 return sorted;
}
