import { Pool, neonConfig } from '@neondatabase/serverless';
import ws from 'ws';
import type { NflMarketGame, NflPlayerMarket } from './nflMarkets.js';

neonConfig.webSocketConstructor=ws;
let pool:Pool|null=null;let ready:Promise<void>|null=null;
function db(){if(!process.env.DATABASE_URL)return null;if(!pool)pool=new Pool({connectionString:process.env.DATABASE_URL});return pool;}
async function ensure(){if(ready)return ready;const c=db();if(!c)return;ready=c.query(`
CREATE TABLE IF NOT EXISTS nfl_td_prediction_history(
 id text PRIMARY KEY,game_id text NOT NULL,game_start_at timestamptz NOT NULL,market text NOT NULL,player text NOT NULL,
 model_version text NOT NULL,model_probability real NOT NULL,market_probability real,best_odds integer,best_book text,
 edge_points real,expected_value real,confidence text,quote_count integer,captured_at timestamptz NOT NULL DEFAULT now(),
 outcome boolean,first_td_player text,graded_at timestamptz
);
CREATE INDEX IF NOT EXISTS nfl_td_prediction_game_idx ON nfl_td_prediction_history(game_id,market);
CREATE INDEX IF NOT EXISTS nfl_td_prediction_graded_idx ON nfl_td_prediction_history(graded_at,game_start_at DESC);
`).then(()=>undefined).catch(e=>{ready=null;throw e});return ready;}
function norm(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');}
function id(gameId:string,market:string,player:string){return `${gameId}:${market}:${norm(player)}:nfl-td-v2`;}
export async function captureNflTdPredictions(game:NflMarketGame){const c=db();if(!c)return;await ensure();const start=new Date(game.date);if(!Number.isFinite(start.getTime())||start.getTime()<=Date.now())return;const rows:Array<{market:string;p:NflPlayerMarket}>=[];for(const p of game.anytimeTd)rows.push({market:'anytime',p});for(const p of game.firstTd)rows.push({market:'first',p});for(const {market,p} of rows){if(p.modelProbability==null)continue;await c.query(`INSERT INTO nfl_td_prediction_history(id,game_id,game_start_at,market,player,model_version,model_probability,market_probability,best_odds,best_book,edge_points,expected_value,confidence,quote_count) VALUES($1,$2,$3,$4,$5,'nfl-td-v2',$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(id) DO NOTHING`,[id(game.id,market,p.player),game.id,start,market,p.player,p.modelProbability,p.impliedProbability,p.bestOdds,p.bestBook,p.edgePoints??null,p.expectedValue??null,p.confidence??null,p.quoteCount]);}}
async function gameResult(gameId:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/nfl/summary?event=${encodeURIComponent(gameId)}`,{signal:controller.signal,headers:{'User-Agent':'PreziTools/1.0'}});if(!r.ok)return null;const x:any=await r.json();const comp=x?.header?.competitions?.[0];if(!(comp?.status?.type?.completed===true||comp?.status?.type?.state==='post'))return null;const scorers=new Set<string>();let first:string|null=null;const plays:any[]=x?.plays??x?.drives?.previous?.flatMap((d:any)=>d?.plays??[])??[];for(const play of plays){const text=String(play?.text??play?.shortText??'');if(!/touchdown/i.test(text))continue;const athletes:any[]=play?.participants??play?.athletes??[];let name=athletes.find((a:any)=>a?.athlete?.displayName)?.athlete?.displayName??null;if(!name){const m=text.match(/^([A-Z][A-Za-z.'-]+(?:\s+[A-Z][A-Za-z.'-]+)+)/);name=m?.[1]??null;}if(name){scorers.add(norm(name));if(!first)first=name;}}
return{scorers,first};}catch{return null}finally{clearTimeout(timer)}}
export async function gradePendingNflTdPredictions(limit=12){const c=db();if(!c)return 0;await ensure();const q=await c.query(`SELECT DISTINCT game_id FROM nfl_td_prediction_history WHERE graded_at IS NULL AND game_start_at<now()-interval '3 hours' ORDER BY game_id LIMIT $1`,[Math.max(1,Math.min(limit,50))]);let graded=0;for(const row of q.rows){const result=await gameResult(String(row.game_id));if(!result)continue;const preds=await c.query(`SELECT id,market,player FROM nfl_td_prediction_history WHERE game_id=$1 AND graded_at IS NULL`,[row.game_id]);for(const p of preds.rows){const hit=p.market==='first'?!!result.first&&norm(String(p.player))===norm(result.first):result.scorers.has(norm(String(p.player)));await c.query(`UPDATE nfl_td_prediction_history SET outcome=$2,first_td_player=$3,graded_at=now() WHERE id=$1 AND graded_at IS NULL`,[p.id,hit,result.first]);}graded++;}return graded;}
function n(v:any){return v==null?null:Number(v)}
export async function getNflTdPerformance(days=90){const c=db();if(!c)return{database:false,modelVersion:'nfl-td-v2',captured:0,graded:0,markets:[]};await ensure();const d=Math.max(1,Math.min(days,365));const r=await c.query(`WITH s AS(SELECT * FROM nfl_td_prediction_history WHERE captured_at>=now()-($1::text||' days')::interval),g AS(SELECT * FROM s WHERE graded_at IS NOT NULL) SELECT market,count(*) sample_size,avg((outcome::int)::float) hit_rate,avg(model_probability)/100 avg_model,avg(market_probability)/100 avg_market,avg(power(model_probability/100.0-(outcome::int),2)) brier,avg(-(outcome::int)*ln(greatest(model_probability/100.0,0.001))-(1-(outcome::int))*ln(greatest(1-model_probability/100.0,0.001))) log_loss,avg(power(market_probability/100.0-(outcome::int),2)) market_brier,avg(CASE WHEN outcome THEN CASE WHEN best_odds>0 THEN best_odds/100.0 ELSE 100.0/abs(best_odds) END ELSE -1 END) roi FROM g GROUP BY market ORDER BY market`,[d]);const counts=await c.query(`SELECT count(*) captured,count(*) FILTER(WHERE graded_at IS NOT NULL) graded FROM nfl_td_prediction_history WHERE captured_at>=now()-($1::text||' days')::interval`,[d]);return{database:true,modelVersion:'nfl-td-v2',windowDays:d,captured:Number(counts.rows[0]?.captured??0),graded:Number(counts.rows[0]?.graded??0),markets:r.rows.map(x=>({market:x.market,sampleSize:Number(x.sample_size),hitRate:n(x.hit_rate),averageModelProbability:n(x.avg_model),averageMarketProbability:n(x.avg_market),brierScore:n(x.brier),logLoss:n(x.log_loss),marketBrierScore:n(x.market_brier),flatUnitRoi:n(x.roi)}))};}
