const NHL_STATS='https://api.nhle.com/stats/rest/en';
const CACHE_MS=6*60*60*1000;
export const NHL_MONEYLINE_VERSION='nhl-moneyline-v2-independent';
export type NhlMoneylineModel={team:string;modelProbability:number;marketProbability:number;edgePoints:number;expectedValue:number;qualifies:boolean;confidence:'watch'|'strong'|'elite';reasons:string[];modelVersion:string;dataStatus:'modeled'};
type TeamRow={teamFullName?:string;teamAbbrev?:string;gamesPlayed?:number;wins?:number;losses?:number;otLosses?:number;goalsFor?:number;goalsAgainst?:number;goalDifferential?:number;points?:number;shotsForPerGame?:number;shotsAgainstPerGame?:number;powerPlayPct?:number;penaltyKillPct?:number};
let cache:{expires:number;season:number;rows:TeamRow[]}|null=null;
function clamp(v:number,min:number,max:number){return Math.max(min,Math.min(max,v))}
function norm(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function implied(o:number){return o>0?100/(o+100):Math.abs(o)/(Math.abs(o)+100)}
function profit(o:number){return o>0?o/100:100/Math.abs(o)}
function ev(p:number,o:number){const x=p/100;return x*profit(o)-(1-x)}
function seasonId(d=new Date()){const y=d.getUTCFullYear(),m=d.getUTCMonth()+1;return m>=7?Number(`${y}${y+1}`):Number(`${y-1}${y}`)}
function previousSeason(s:number){const a=Math.floor(s/10000)-1;return Number(`${a}${a+1}`)}
async function standings(season:number){if(cache&&cache.expires>Date.now()&&cache.season===season)return cache.rows;const url=`${NHL_STATS}/team/summary?isAggregate=false&isGame=false&sort=[{%22property%22:%22points%22,%22direction%22:%22DESC%22}]&start=0&limit=-1&cayenneExp=seasonId=${season}%20and%20gameTypeId=2`;const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'PreziTools/1.0','Accept':'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const p=await r.json() as any;const rows=Array.isArray(p?.data)?p.data:[];cache={expires:Date.now()+CACHE_MS,season,rows};return rows}finally{clearTimeout(t)}}
function find(rows:TeamRow[],team:string){const t=norm(team);const exact=rows.filter(r=>norm(String(r.teamFullName??''))===t||norm(String(r.teamAbbrev??''))===t);if(exact.length===1)return exact[0];const fuzzy=rows.filter(r=>{const n=norm(String(r.teamFullName??''));return n&&t&&(n.includes(t)||t.includes(n))});return fuzzy.length===1?fuzzy[0]:null}
export async function modelMoneyline(team:string,opponent:string,bestOdds:number):Promise<NhlMoneylineModel|null>{if(!Number.isFinite(bestOdds)||bestOdds===0)return null;const current=seasonId();let a:TeamRow|null=null,b:TeamRow|null=null,source=current;for(const season of[current,previousSeason(current)]){try{const rows=await standings(season);a=find(rows,team);b=find(rows,opponent);if(a&&b){source=season;break}}catch{}}if(!a||!b)return null;const ag=Number(a.gamesPlayed??0),bg=Number(b.gamesPlayed??0);if(ag<20||bg<20)return null;const aw=Number(a.wins??0),bw=Number(b.wins??0),aot=Number(a.otLosses??0),bot=Number(b.otLosses??0);const ap=(aw+aot*.45)/ag,bp=(bw+bot*.45)/bg;const ad=Number(a.goalDifferential??(Number(a.goalsFor??0)-Number(a.goalsAgainst??0)))/ag,bd=Number(b.goalDifferential??(Number(b.goalsFor??0)-Number(b.goalsAgainst??0)))/bg;const strength=clamp((ap-bp)*.62+(ad-bd)*.055,-.24,.24);const rawIndependent=clamp(50+strength*100,27,73);const evidenceWeight=clamp(Math.min(ag,bg)/60,.45,.90);const model=clamp(50+(rawIndependent-50)*evidenceWeight,28,72);const market=implied(bestOdds)*100;const edge=model-market,e=ev(model,bestOdds);const qualifies=edge>=3&&e>=.06&&model>=42;const confidence=qualifies&&edge>=5&&e>=.12?'elite':qualifies?'strong':'watch';return{team,modelProbability:+model.toFixed(1),marketProbability:+market.toFixed(1),edgePoints:+edge.toFixed(1),expectedValue:+e.toFixed(3),qualifies,confidence,reasons:[`${(ap*100).toFixed(1)}% adjusted result rate over ${ag} games`,`${ad>=0?'+':''}${ad.toFixed(2)} goal differential/game`,`${opponent}: ${(bp*100).toFixed(1)}% adjusted result rate, ${bd>=0?'+':''}${bd.toFixed(2)} goal differential/game`,`independent team-strength estimate shrunk toward 50% for sample stability; sportsbook price is used only for edge and EV`,`baseline: NHL Stats ${source}`],modelVersion:NHL_MONEYLINE_VERSION,dataStatus:'modeled'};}
