import { propLineGet } from './propLineClient.js';
import { modelGoalScorer, NHL_MODEL_VERSION, type NhlConfidence } from './nhlModels.js';

const SPORT_KEYS=['icehockey_nhl','hockey_nhl'] as const;
const CACHE_MS=15*60*1000;
type Quote={bookmaker:string;bookmakerKey:string;americanOdds:number;updatedAt:string|null};
type Outcome={name?:string;description?:string;price?:number;book_updated_at?:string;last_change_at?:string};type Market={key?:string;outcomes?:Outcome[]};type Book={key?:string;title?:string;last_update?:string;markets?:Market[]};type OddsRow={id?:string|number;event_id?:string|number;home_team?:string;away_team?:string;commence_time?:string;bookmakers?:Book[]};
export type NhlScorerMarket={player:string;bestOdds:number;bestBook:string;impliedProbability:number;quoteCount:number;quotes:Quote[];modelProbability?:number;edgePoints?:number;expectedValue?:number;confidence?:NhlConfidence;qualifies?:boolean;reasons?:string[];dataStatus:'modeled'|'not-ready';modelVersion?:string};
export type NhlMarketGame={id:string;date:string;away:string;home:string;moneyline:{away:Quote[];home:Quote[]}|null;anytimeGoal:NhlScorerMarket[];firstGoal:NhlScorerMarket[];qualified:{anytimeGoal:boolean;firstGoal:boolean}};
export type NhlMarketFeed={source:string;modelVersion:string;marketStatus:'available'|'unavailable'|'disabled';updatedAt:string;games:NhlMarketGame[];health:{rawScorers:number;modeledScorers:number;notReadyScorers:number;coveragePct:number}};
let cache:{expires:number;value:NhlMarketFeed}|null=null;
function norm(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function implied(o:number){return(o>0?100/(o+100):Math.abs(o)/(Math.abs(o)+100))*100}
function rows(p:unknown):OddsRow[]{if(Array.isArray(p))return p as OddsRow[];if(p&&typeof p==='object'){const o=p as any;for(const k of['events','data','odds'])if(Array.isArray(o[k]))return o[k];if(o.data&&typeof o.data==='object')for(const k of['events','data','odds'])if(Array.isArray(o.data[k]))return o.data[k];}return[]}
function q(book:Book,o:Outcome):Quote|null{const price=Number(o.price);if(!Number.isFinite(price)||price===0)return null;return{bookmaker:String(book.title??book.key??'Sportsbook'),bookmakerKey:String(book.key??''),americanOdds:price,updatedAt:o.book_updated_at??o.last_change_at??book.last_update??null}}
function scorerMarkets(row:OddsRow,key:string){const by=new Map<string,{player:string;quotes:Quote[]}>();for(const book of row.bookmakers??[])for(const market of book.markets??[]){if(market.key!==key)continue;for(const o of market.outcomes??[]){const name=String(o.description&&!/^(yes|no)$/i.test(o.description)?o.description:o.name??'').replace(/\s*\([A-Z0-9]{2,5}\)\s*$/i,'').trim();if(!name||/^(yes|no)$/i.test(name))continue;const quote=q(book,o);if(!quote)continue;const k=norm(name),e=by.get(k)??{player:name,quotes:[]};e.quotes.push(quote);by.set(k,e)}}return[...by.values()].map(e=>{e.quotes.sort((a,b)=>b.americanOdds-a.americanOdds);const best=e.quotes[0];return{player:e.player,bestOdds:best.americanOdds,bestBook:best.bookmaker,impliedProbability:implied(best.americanOdds),quoteCount:e.quotes.length,quotes:e.quotes}}).sort((a,b)=>b.impliedProbability-a.impliedProbability).slice(0,24)}
function moneyline(row:OddsRow){const away:Quote[]=[],home:Quote[]=[];for(const book of row.bookmakers??[])for(const m of book.markets??[]){if(m.key!=='h2h')continue;for(const o of m.outcomes??[]){const quote=q(book,o);if(!quote)continue;const name=norm(String(o.name??o.description??''));if(name===norm(row.away_team??''))away.push(quote);if(name===norm(row.home_team??''))home.push(quote)}}away.sort((a,b)=>b.americanOdds-a.americanOdds);home.sort((a,b)=>b.americanOdds-a.americanOdds);return away.length&&home.length?{away,home}:null}
async function model(raw:ReturnType<typeof scorerMarkets>,market:'anytime'|'first',teams:string[]){const out:NhlScorerMarket[]=[];for(const r of raw){let hit=null;for(const team of teams){hit=await modelGoalScorer(r.player,team,r.bestOdds,market);if(hit)break}if(!hit){out.push({...r,dataStatus:'not-ready',qualifies:false,reasons:['DATA NOT READY — no unique NHL statistical baseline was resolved. This is not an Official Play.'],modelVersion:NHL_MODEL_VERSION});continue}out.push({...r,dataStatus:'modeled',modelProbability:hit.modelProbability,edgePoints:hit.edgePoints,expectedValue:hit.expectedValue,confidence:hit.confidence,qualifies:hit.qualifies,reasons:hit.reasons,modelVersion:NHL_MODEL_VERSION})}return out.sort((a,b)=>Number(b.qualifies)-Number(a.qualifies)||(b.expectedValue??-99)-(a.expectedValue??-99)).slice(0,3)}
export async function fetchNhlMarkets():Promise<NhlMarketFeed>{if(cache&&cache.expires>Date.now())return cache.value;const health={rawScorers:0,modeledScorers:0,notReadyScorers:0,coveragePct:0};if(!process.env.PROPLINE_API_KEY?.trim()){const value:NhlMarketFeed={source:'PropLine + NHL Stats + PreziTools NHL Model',modelVersion:NHL_MODEL_VERSION,marketStatus:'disabled',updatedAt:new Date().toISOString(),games:[],health};cache={expires:Date.now()+300000,value};return value}let raw:OddsRow[]=[];for(const sport of SPORT_KEYS){try{const p=await propLineGet<unknown>(`/sports/${sport}/odds?markets=h2h`,{cacheMs:CACHE_MS});raw=rows(p);if(raw.length)break}catch{}}const games:NhlMarketGame[]=[];for(const row of raw){const id=String(row.id??row.event_id??'');if(!id)continue;let anytimeRaw:ReturnType<typeof scorerMarkets>=[],firstRaw:ReturnType<typeof scorerMarkets>=[];for(const sport of SPORT_KEYS){try{const p=await propLineGet<unknown>(`/sports/${sport}/events/${encodeURIComponent(id)}/odds?markets=player_anytime_goal,player_1st_goal`,{cacheMs:30*60*1000});anytimeRaw=scorerMarkets(rows(p)[0]??p as OddsRow,'player_anytime_goal');firstRaw=scorerMarkets(rows(p)[0]??p as OddsRow,'player_1st_goal');if(anytimeRaw.length||firstRaw.length)break}catch{}}health.rawScorers+=anytimeRaw.length+firstRaw.length;const teams=[String(row.away_team??''),String(row.home_team??'')],anytime=await model(anytimeRaw,'anytime',teams),first=await model(firstRaw,'first',teams);health.modeledScorers+=anytime.filter(x=>x.dataStatus==='modeled').length+first.filter(x=>x.dataStatus==='modeled').length;health.notReadyScorers+=anytime.filter(x=>x.dataStatus==='not-ready').length+first.filter(x=>x.dataStatus==='not-ready').length;games.push({id,date:String(row.commence_time??''),away:teams[0],home:teams[1],moneyline:moneyline(row),anytimeGoal:anytime,firstGoal:first,qualified:{anytimeGoal:anytime.some(x=>x.qualifies),firstGoal:first.some(x=>x.qualifies)}})}health.coveragePct=health.rawScorers?+((health.modeledScorers/health.rawScorers)*100).toFixed(1):0;console.info(`[NHL Goal Health] raw=${health.rawScorers} modeled=${health.modeledScorers} notReady=${health.notReadyScorers} coverage=${health.coveragePct}%`);const value:NhlMarketFeed={source:'PropLine + NHL Stats + PreziTools NHL Model',modelVersion:NHL_MODEL_VERSION,marketStatus:games.length?'available':'unavailable',updatedAt:new Date().toISOString(),games,health};cache={expires:Date.now()+CACHE_MS,value};return value}
