import { gradeNhlPrediction, listNhlPredictions, type NhlTrackedPrediction } from './nhlTracking.js';
const NHL_WEB='https://api-web.nhle.com/v1';
function norm(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function profit(o:number){return o>0?o/100:100/Math.abs(o)}
async function boxscore(id:string){const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(`${NHL_WEB}/gamecenter/${encodeURIComponent(id)}/boxscore`,{signal:c.signal,headers:{Accept:'application/json','User-Agent':'PreziTools/1.0'}});if(!r.ok)return null;return await r.json() as any}catch{return null}finally{clearTimeout(t)}}
async function playByPlay(id:string){const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(`${NHL_WEB}/gamecenter/${encodeURIComponent(id)}/play-by-play`,{signal:c.signal,headers:{Accept:'application/json','User-Agent':'PreziTools/1.0'}});if(!r.ok)return null;return await r.json() as any}catch{return null}finally{clearTimeout(t)}}
function finalGame(b:any){const s=String(b?.gameState??b?.gameScheduleState??'').toUpperCase();return['FINAL','OFF'].includes(s)}
function winner(b:any){const h=Number(b?.homeTeam?.score),a=Number(b?.awayTeam?.score);if(!Number.isFinite(h)||!Number.isFinite(a)||h===a)return null;return h>a?String(b?.homeTeam?.name?.default??b?.homeTeam?.abbrev??''):String(b?.awayTeam?.name?.default??b?.awayTeam?.abbrev??'')}
function goals(p:any){return(Array.isArray(p?.plays)?p.plays:[]).filter((x:any)=>String(x?.typeDescKey??'').toLowerCase()==='goal'&&!x?.details?.eventOwnerTeamId===false)}
function scorerName(g:any){const d=g?.details??{};return String(d.scoringPlayerName?.default??d.scorerName?.default??d.scoringPlayer?.name?.default??'')}
async function gradeOne(row:NhlTrackedPrediction,b:any,p:any){if(row.market==='moneyline'){const w=winner(b);if(!w)return false;await gradeNhlPrediction(row.id,norm(w)===norm(row.selection)?'won':'lost');return true}const gs=goals(p);if(!gs.length){await gradeNhlPrediction(row.id,'lost');return true}if(row.market==='first-goal'){const n=scorerName(gs[0]);if(!n)return false;await gradeNhlPrediction(row.id,norm(n)===norm(row.selection)?'won':'lost');return true}const names=gs.map(scorerName).filter(Boolean);if(!names.length)return false;await gradeNhlPrediction(row.id,names.some(n=>norm(n)===norm(row.selection))?'won':'lost');return true}
export async function gradePendingNhlPredictions(limit=40){const pending=(await listNhlPredictions()).filter(x=>x.status==='pending').slice(0,limit),byEvent=new Map<string,NhlTrackedPrediction[]>();for(const r of pending){const a=byEvent.get(r.eventId)??[];a.push(r);byEvent.set(r.eventId,a)}let graded=0;for(const[id,rs]of byEvent){const b=await boxscore(id);if(!b||!finalGame(b))continue;const needsGoals=rs.some(r=>r.market!=='moneyline'),p=needsGoals?await playByPlay(id):null;if(needsGoals&&!p)continue;for(const r of rs)if(await gradeOne(r,b,p))graded++}return{checked:pending.length,graded}}
export async function getNhlPerformance(days=90){const cutoff=Date.now()-days*86400000,rows=(await listNhlPredictions()).filter(r=>new Date(r.eventDate||r.recordedAt).getTime()>=cutoff),graded=rows.filter(r=>['won','lost','push','void'].includes(r.status)),settled=graded.filter(r=>r.status==='won'||r.status==='lost'),wins=settled.filter(r=>r.status==='won').length,losses=settled.length-wins;let units=0;for(const r of settled)units+=r.status==='won'?profit(r.americanOdds):-1;const risked=settled.length;const markets=['anytime-goal','first-goal','moneyline'].map(m=>{const x=settled.filter(r=>r.market===m),w=x.filter(r=>r.status==='won').length;let u=0;for(const r of x)u+=r.status==='won'?profit(r.americanOdds):-1;return{market:m,picks:x.length,wins:w,losses:x.length-w,hitRate:x.length?+(w/x.length*100).toFixed(1):null,units:+u.toFixed(2),roi:x.length?+(u/x.length*100).toFixed(1):null}});return{windowDays:days,modelPolicy:'frozen-forward-test',automaticRewriting:false,totalRecorded:rows.length,pending:rows.filter(r=>r.status==='pending').length,graded:graded.length,wins,losses,hitRate:settled.length?+(wins/settled.length*100).toFixed(1):null,units:+units.toFixed(2),roi:risked?+(units/risked*100).toFixed(1):null,markets,recent:rows.slice(0,100)}}
