import { Pool, neonConfig } from '@neondatabase/serverless';
import ws from 'ws';
neonConfig.webSocketConstructor=ws;
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL}):null;
export const NHL_LEDGER_VERSION='nhl-v1-ledger';
export type NhlTrackedMarket='anytime-goal'|'first-goal'|'moneyline';
export type NhlTrackedPrediction={id:string;eventId:string;eventDate:string;market:NhlTrackedMarket;selection:string;team?:string;opponent?:string;americanOdds:number;bookmaker:string;modelProbability:number;marketProbability:number;edgePoints:number;expectedValue:number;modelVersion:string;recordedAt:string;status:'pending'|'won'|'lost'|'push'|'void';gradedAt?:string};
type Pick=Omit<NhlTrackedPrediction,'id'|'recordedAt'|'status'>;
function key(p:Pick){return[p.eventId,p.market,p.selection,p.modelVersion].join('|').toLowerCase()}
function idFor(p:Pick){return`nhl-${Buffer.from(key(p)).toString('base64url').slice(0,80)}`}
const fallback=new Map<string,NhlTrackedPrediction>();
export async function recordNhlPrediction(p:Pick){const id=idFor(p),recordedAt=new Date().toISOString();if(!pool){const existing=fallback.get(key(p));if(existing)return existing;const row:NhlTrackedPrediction={...p,id,recordedAt,status:'pending'};fallback.set(key(p),row);return row}try{const r=await pool.query(`INSERT INTO nhl_prediction_ledger (id,event_id,event_date,market,selection,team,opponent,american_odds,bookmaker,model_probability,market_probability,edge_points,expected_value,model_version,recorded_at,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,'pending') ON CONFLICT (event_id,market,selection,model_version) DO NOTHING RETURNING *`,[id,p.eventId,p.eventDate,p.market,p.selection,p.team??null,p.opponent??null,p.americanOdds,p.bookmaker,p.modelProbability,p.marketProbability,p.edgePoints,p.expectedValue,p.modelVersion,recordedAt]);if(r.rows[0])return mapRow(r.rows[0]);const e=await pool.query(`SELECT * FROM nhl_prediction_ledger WHERE event_id=$1 AND market=$2 AND selection=$3 AND model_version=$4 LIMIT 1`,[p.eventId,p.market,p.selection,p.modelVersion]);return e.rows[0]?mapRow(e.rows[0]):null}catch(e){console.warn('[NHL Ledger] persistent record failed; prediction not rewritten',e);return null}}
function mapRow(r:any):NhlTrackedPrediction{return{id:String(r.id),eventId:String(r.event_id),eventDate:String(r.event_date),market:r.market,selection:String(r.selection),team:r.team??undefined,opponent:r.opponent??undefined,americanOdds:Number(r.american_odds),bookmaker:String(r.bookmaker),modelProbability:Number(r.model_probability),marketProbability:Number(r.market_probability),edgePoints:Number(r.edge_points),expectedValue:Number(r.expected_value),modelVersion:String(r.model_version),recordedAt:new Date(r.recorded_at).toISOString(),status:r.status,gradedAt:r.graded_at?new Date(r.graded_at).toISOString():undefined}}
export async function listNhlPredictions(){if(!pool)return[...fallback.values()].sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt));try{const r=await pool.query(`SELECT * FROM nhl_prediction_ledger ORDER BY recorded_at DESC LIMIT 2000`);return r.rows.map(mapRow)}catch{return[]}}
export async function gradeNhlPrediction(id:string,status:'won'|'lost'|'push'|'void'){if(!pool){const row=[...fallback.values()].find(v=>v.id===id);if(!row||row.status!=='pending')return row??null;row.status=status;row.gradedAt=new Date().toISOString();return row}const gradedAt=new Date().toISOString();const r=await pool.query(`UPDATE nhl_prediction_ledger SET status=$2,graded_at=$3 WHERE id=$1 AND status='pending' RETURNING *`,[id,status,gradedAt]);return r.rows[0]?mapRow(r.rows[0]):null}
export async function nhlLedgerSummary(){const rows=await listNhlPredictions(),graded=rows.filter(r=>r.status!=='pending'),won=graded.filter(r=>r.status==='won').length,lost=graded.filter(r=>r.status==='lost').length;return{version:NHL_LEDGER_VERSION,persistent:Boolean(pool),total:rows.length,pending:rows.length-graded.length,graded:graded.length,won,lost,hitRate:won+lost?+((won/(won+lost))*100).toFixed(1):null,rows}}
