import { useState } from "react";
import { Link, useLocation } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { cn } from "@/lib/utils";
import { CheckCircle2, ChevronDown, Sparkles, XCircle } from "lucide-react";
function BasketballIcon({className}:{className?:string}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className={className} aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 3c2.2 2.6 3.3 5.6 3.3 9S14.2 18.4 12 21M12 3C9.8 5.6 8.7 8.6 8.7 12s1.1 6.4 3.3 9M3.4 9.2c2.6.8 5.5 1.2 8.6 1.2s6-.4 8.6-1.2M3.4 14.8c2.6-.8 5.5-1.2 8.6-1.2s6 .4 8.6 1.2"/></svg>}
function BaseballIcon({className}:{className?:string}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className={className} aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M7.1 4.5c1.7 1.7 2.6 3.8 2.6 6.2s-.9 4.5-2.6 6.2M16.9 7.1c-1.7 1.7-2.6 3.8-2.6 6.2s.9 4.5 2.6 6.2"/></svg>}
function FootballIcon({className}:{className?:string}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className={className}><path d="M19.8 4.2c-3.1-3.1-9.2-.8-12.7 2.7S1.3 16.5 4.2 19.8c3.1 3.1 9.2.8 12.7-2.7s5.8-9.6 2.9-12.9Z"/><path d="m8.5 15.5 7-7"/></svg>}
function HockeyIcon({className}:{className?:string}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className={className}><path d="m15.8 3-2.7 11.2c-.4 1.6-1.8 2.8-3.5 2.8H5.5c-1.4 0-2.5 1.1-2.5 2.5S4.1 22 5.5 22h5.1c3.4 0 6.4-2.3 7.2-5.6L21 3"/></svg>}
type SportIcon="best"|"basketball"|"baseball"|"football"|"hockey";type Outcome={id:string;sport:string;market:string;matchup:string;pick:string;probability:number;result:"won"|"lost";actual:string;href:string};type OutcomePayload={date:string;total:number;wins:number;losses:number;outcomes:Outcome[]};
const navItems=[{label:"Best Plays",path:"/",icon:"best",glow:"nav-glow-best"},{label:"NBA",path:"/nba",icon:"basketball",glow:"nav-glow-nba"},{label:"WNBA",path:"/wnba",icon:"basketball",glow:"nav-glow-wnba"},{label:"MLB",path:"/mlb",icon:"baseball",glow:"nav-glow-mlb"},{label:"KBO / NPB",path:"/kbo-npb",icon:"baseball",glow:"nav-glow-mlb"},{label:"NFL",path:"/nfl",icon:"football",glow:"nav-glow-nfl"},{label:"NHL",path:"/nhl",icon:"hockey",glow:"nav-glow-nhl"}] as const;
function NavIcon({type}:{type:SportIcon}){const c="w-4 h-4 shrink-0";if(type==="basketball")return <BasketballIcon className={c}/>;if(type==="baseball")return <BaseballIcon className={c}/>;if(type==="football")return <FootballIcon className={c}/>;if(type==="hockey")return <HockeyIcon className={c}/>;return <Sparkles className={c}/>}
function YesterdayResults(){const[open,setOpen]=useState(false);const q=useQuery<OutcomePayload>({queryKey:["/api/best-plays/outcomes","yesterday"],queryFn:async()=>{const r=await fetch("/api/best-plays/outcomes?date=yesterday");if(!r.ok)throw new Error();return r.json()},staleTime:300000,refetchInterval:600000,retry:1});const d=q.data,decided=(d?.wins??0)+(d?.losses??0),rate=decided?Math.round((d!.wins/decided)*100):null;return <div className="border-t border-border/45 bg-background/75 backdrop-blur"><div className="max-w-7xl mx-auto px-3 sm:px-4 md:px-6 lg:px-8 py-1.5"><button onClick={()=>setOpen(v=>!v)} className="w-full rounded-xl border border-border/60 bg-card/70 px-3 py-2.5 text-left"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2.5"><CheckCircle2 className="h-4 w-4 text-emerald-500"/><div><div className="text-[11px] font-black">Yesterday&apos;s Results</div><div className="text-[9px] text-muted-foreground">Verified graded Best Plays</div></div></div><div className="flex items-center gap-2">{d&&decided?<span className="font-mono text-xs font-black"><span className="text-emerald-500">{d.wins}W</span> – <span className="text-rose-500">{d.losses}L</span>{rate!==null&&` · ${rate}%`}</span>:<span className="text-[10px] text-muted-foreground">{q.isLoading?"Loading…":"No graded plays"}</span>}<ChevronDown className={cn("h-4 w-4",open&&"rotate-180")}/></div></div></button>{open&&<div className="mt-1.5 max-h-[340px] overflow-y-auto rounded-xl border border-border/60 bg-card/80">{d?.outcomes?.length?d.outcomes.map(row=><Link key={row.id} href={row.href}><div className="grid grid-cols-[52px_1fr_auto] items-center gap-2 border-b border-border/40 px-3 py-3"><div className="text-[9px] font-black text-muted-foreground">{row.sport}</div><div><div className="text-xs font-bold">{row.pick}</div><div className="text-[9px] text-muted-foreground">{row.market} · {row.matchup}</div></div>{row.result==="won"?<CheckCircle2 className="h-4 w-4 text-emerald-500"/>:<XCircle className="h-4 w-4 text-rose-500"/>}</div></Link>):<div className="p-5 text-center text-xs text-muted-foreground">No verified graded plays for yesterday yet.</div>}</div>}</div></div>}
export default function Navigation(){const[location]=useLocation();return <nav className="site-sports-nav border-b bg-card sticky top-14 z-40"><div className="max-w-7xl mx-auto px-3 sm:px-4 md:px-6 lg:px-8"><div className="flex items-center gap-1 overflow-x-auto py-1.5 scrollbar-none md:justify-center">{navItems.map(item=>{const active=location===item.path||(item.path!=="/"&&location.startsWith(`${item.path}/`));return <Link key={item.path} href={item.path}><span className={cn("sport-nav-tab min-h-10 flex items-center gap-1.5 rounded-lg px-3 sm:px-4 py-2 text-[11px] sm:text-xs font-semibold whitespace-nowrap cursor-pointer",item.glow,active?"sport-nav-active":"text-muted-foreground")}><NavIcon type={item.icon}/>{item.label}</span></Link>})}</div></div>{location==="/"&&<YesterdayResults/>}</nav>}
